// Tier 3: Intermediate. Tactical weapons, positional fundamentals, first
// endgame technique.
import type { Tier } from '../schema'
import { text, demo, quiz, drill, right, wrong, playout, gtmStep, guess } from '../kit'

const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'

export const intermediate: Tier = {
  id: 'intermediate',
  n: 3,
  title: 'Intermediate',
  tagline: 'Tactical weapons, positional fundamentals, endgame technique.',
  color: '#3f8f8a',
  levels: [
    {
      id: 'int-01',
      n: 1,
      title: 'Double attack',
      subtitle: 'Any piece can hit two targets at once.',
      minutes: 9,
      concepts: ['doubleAttack', 'fork'],
      steps: [
        quiz('Retrieval first', 'From the Beginner tier: what does the mnemonic LPDO stand for?', [
          right('Loose Pieces Drop Off', 'Undefended pieces are the targets every double attack is looking for.'),
          wrong('Long Pawns Defend Openings', 'Not a real mnemonic. The real one is about undefended pieces.'),
          wrong('Look, Plan, Deliver, Occupy', 'Close in spirit, but the classic phrase is Loose Pieces Drop Off.'),
        ]),
        text(
          'Two targets, one move',
          [
            'The fork is the knight\u2019s specialty, but every piece can attack two things in one move. A queen slides to a square that hits one piece on its rank and another on its file. A rook lands on a line that touches two loose pieces.',
            'The recipe is always the same: find two enemy pieces that are undefended or badly defended, then look for one square that attacks them both. Loose pieces drop off, so aim at loose ones first.',
          ],
          'One move, two victims: scan for pieces that share a line.',
        ),
        demo(
          'The shared rank',
          ['The rook on a5 and the bishop on g5 both stand on rank 5. The queen on d1 can reach the middle of that rank in one move.'],
          '6k1/8/8/r5b1/8/8/8/3QK3 w - - 0 1',
          { marks: [{ square: 'd5', color: 'green' }], caption: 'Qd5 hits both pieces at once' },
        ),
        drill('Hit them both', '6k1/8/8/r5b1/8/8/8/3QK3 w - - 0 1', ['Qd5+'], 'Attack the rook and the bishop in one move', 'The queen rides to d5: rank 5 hits both pieces, and the diagonal checks the king.', 'Qd5 with check. Two loose pieces, one move. One of them falls next turn no matter what Black saves.'),
        drill('Rook double attack', '3r2k1/8/8/8/8/8/5K2/R6b w - - 0 1', ['Rd1'], 'The bishop on h1 and the rook on d8 are both in reach. Find the square.', 'd1 sits on the d-file and the first rank at the same time.', 'Rd1. The bishop on h1 and the rook on d8 are both under fire. Only one can be saved.'),
        quiz('Choosing targets', 'What makes the best double attack?', [
          right('Two targets that are both undefended or worth more than your attacker', 'Then whatever your opponent saves, you win material.'),
          wrong('Any two pieces anywhere', 'A double attack against two defended, cheap pieces usually wins nothing.'),
          wrong('Two attacks against the king', 'There is only one king. The second target should be material or a mating square.'),
        ]),
        quiz('The checklist', 'Before playing a double attack, what must you verify?', [
          right('That at least one target falls even after the best defense', 'Count the follow-up: if Black saves one piece, is the other really lost? The math comes first.'),
          wrong('Only that the move looks aggressive', 'Aggressive moves that lose material are just fast losses.'),
          wrong('That your pieces are on good squares', 'Piece placement helps, but the double attack question is about the two targets and the follow-up.'),
        ]),
        drill(
          'The queen double hit',
          'r5k1/8/8/3Q4/8/8/8/4K3 w - - 0 1',
          ['Qd8+', 'Kf7', 'Qxa8'],
          'One queen move hits the king and the rook',
          'The queen and both black pieces share a rank. Walk onto it with check.',
          'Qd8+ forks king and rook along the 8th rank: after the king steps, the rook falls. One move, two jobs.',
        ),
      ],
    },
    {
      id: 'int-02',
      n: 2,
      title: 'Discovered attack',
      subtitle: 'Move one piece, free the one behind it.',
      minutes: 9,
      concepts: ['discoveredAttack', 'doubleAttack'],
      steps: [
        quiz('Retrieval first', 'Which pieces can create a discovered attack?', [
          right('Any two of your pieces sharing a line: the front one moves, the back one fires', 'Files, ranks and diagonals all carry discoveries. The front piece just has to step aside.'),
          wrong('Only knights in front of rooks', 'Knights are the most common front piece, but pawns, bishops and queens all discover too.'),
          wrong('Only queens behind pawns', 'Queens are usually the BACK piece firing the line, not the front.'),
        ]),
        text(
          'The hidden battery',
          [
            'When two of your pieces stand on the same line, the front one blocks the back one. Move the front piece and the back piece suddenly attacks: that is a discovered attack.',
            'If the line points at the king, the moving piece delivers check and a threat at the same time, and your opponent can only parry one. Discovered check is one of the most violent weapons in chess.',
          ],
          'Two pieces on one line: every move of the front piece is a threat.',
        ),
        text(
          'Finding your batteries',
          [
            'Scan your own pieces first: which pairs share a file, rank or diagonal? Each pair is a loaded weapon waiting for the front piece to move.',
            'Then make the front move pay double: with the line opening anyway, the moving piece should capture, check or fork something. A discovered attack where the mover does nothing is half a tactic.',
          ],
          'Find your own shared lines, then make both halves count.',
        ),
        demo(
          'Double check',
          ['The knight on e4 shields the rook on e1 from the king on e8. Nd6 opens the file AND jumps next to the king: double check.'],
          '4k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1',
          { moves: ['Nd6+'], caption: 'The rook checks, the knight checks: nothing blocks a double check' },
        ),
        demo(
          'The queen behind the knight',
          ['More firepower: the queen on e2 waits behind the knight. The knight hops out with check, and the queen fires down the whole e-file at the same time.'],
          '4k3/8/8/8/4N3/8/4Q3/4R1K1 w - - 0 1',
          { moves: ['Nd6+'], caption: 'Queen and knight battery: double check again' },
        ),
        drill('Open the file', '4k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1', ['Nd6+'], 'Attack the king with the rook by moving the knight', 'The e-file is the line. The knight hops to d6, which also checks.', 'Nd6 plus check, twice over. The king must run; the knight also eyes e8.'),
        drill('Free the bishop', 'k7/6pp/8/4N3/8/8/8/1B4K1 w - - 0 1', ['Nf7'], 'The bishop on b2 is tired of waiting behind the knight', 'Any knight move opens the b2-g7 diagonal. Pick the jump that lands next to the king: f7.', 'Nf7. The knight hops toward the king side while the bishop suddenly stares at g7. The pawn is doomed.'),
        quiz('Blocking a check', 'Your opponent delivers a double check (two pieces checking at once). Your options are...', [
          right('Move the king. That is all.', 'Against a double check, blocking and capturing are impossible: two different attackers must both be stopped.'),
          wrong('Block with a piece', 'You would need to block two lines at once. Impossible with one piece.'),
          wrong('Capture the piece that moved', 'The other checker still checks. Only the king move survives.'),
        ]),
        quiz('Who moves, who stays', 'In a discovered attack, which piece should make the move?', [
          right('The front piece, ideally to a square that adds a second threat', 'The rear piece does the damage by staying put. The mover should grab something too if possible.'),
          wrong('The rear piece: it does the hitting', 'The rear piece never moves in a discovered attack. Its power comes from being revealed.'),
          wrong('It makes no difference which one moves', 'The mover is your extra move: use it to attack, capture or improve something.'),
        ]),
      ],
    },
    {
      id: 'int-03',
      n: 3,
      title: 'The zwischenzug',
      subtitle: 'Before recapturing, ask: is there something stronger?',
      minutes: 9,
      concepts: ['calculation', 'tempo'],
      steps: [
        quiz('Retrieval first', 'Against a double check, what is the only legal response?', [
          right('Moving the king', 'Two checkers cannot be blocked or captured with one move. The king walks.'),
          wrong('Blocking with a piece', 'One piece cannot block two lines at once.'),
          wrong('Capturing the checking knight', 'The rook behind it still checks. Capture solves nothing.'),
        ]),
        text(
          'The move in between',
          [
            'A zwischenzug (German for intermediate move) is the habit of refusing the obvious reply. Before recapturing, check whether a check, a threat or a bigger capture comes first.',
            'The most famous beginner trap in chess works because of a zwischenzug: after 1.e4 e5 2.Nf3 Nc6 3.Bc4 Nd4?! 4.Nxe5??, Black does NOT recapture. Qg5 hits the knight on e5 and the g2 pawn at the same time. White grabs material, and Black builds a winning attack on the exposed king.',
          ],
          'Capture, then pause: what is stronger than my recapture?',
        ),
        text(
          'When attention drops',
          [
            'Exchanges are the most dangerous moments on the board, because both players run on autopilot. The recapture feels automatic, and automatic is where zwischenzugs live.',
            'The trigger phrase: after a capture, ask "what else can I do?" If the answer is a check, a fork or a bigger prize, do that first. The board will still be there for the recapture.',
          ],
          'The moment after a capture is the moment to think twice.',
        ),
        demo('The famous refusal', ['Black skips any thought of the knight and inserts Qg5, attacking the knight on e5 and the g2 pawn together. Watch the whole trap unfold.'], START, {
          moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nd4', 'Nxe5', 'Qg5', 'Nxf7', 'Qxg2', 'Rf1', 'Qxe4+'],
          caption: 'Black never recaptured, and White is the one losing material',
        }),
        drill('Refuse the recapture', 'r1bqkbnr/pppp1ppp/8/4N3/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4', ['Qg5'], 'White just took the e5 pawn with his knight. Punish the greed instead of chasing the knight.', 'Find the square that attacks the knight on e5 and the pawn on g2 at once. The queen lands there in one move: g5.', 'Qg5. The zwischenzug. The knight on e5 is attacked, the g2 pawn hangs, and White cannot hold both.'),
        quiz('Zwischenzug trigger', 'When is the zwischenzug most likely to work?', [
          right('Right after a capture or exchange, when attention drops', 'Exchanges are the moment everyone plays automatically. That is where the extra check or threat lands.'),
          wrong('Only in the opening', 'It happens in every phase, especially in tactics-rich middlegames.'),
          wrong('Only when you are losing', 'It wins material at any score.'),
        ]),
        quiz('The trap sequence', 'In the trap from the demo, what exactly was the zwischenzug?', [
          right('Qg5, attacking the e5 knight and the g2 pawn in one move', 'Two threats from one queen. White could not parry both and lost material hand over fist.'),
          wrong('Qxe4, taking the pawn immediately', 'That is the automatic move the trap exists to punish. The queen move came first.'),
          wrong('Nxc2+, grabbing a fork', 'The knight was on d4 and never moved. The queen did all the work.'),
        ]),
        quiz('When to just recapture', 'When is immediate recapture the right choice after a capture?', [
          right('When no intermediate move wins material or forces mate', 'The zwischenzug needs a REAL second threat. Without one, plain recapture is best.'),
          wrong('Never: always play something in between first', 'Random in-between moves hang material. The zwischenzug must be calculated, not guessed.'),
          wrong('Whenever you are the stronger player', 'Strength does not change the math. A false zwischenzug just loses material.'),
        ]),
      ],
    },
    {
      id: 'int-04',
      n: 4,
      title: 'Deflection',
      subtitle: 'Pull the defender away, then strike.',
      minutes: 9,
      concepts: ['removingDefender', 'mate'],
      steps: [
        quiz('Retrieval first', 'What is a zwischenzug in one sentence?', [
          right('An intermediate move played instead of the expected recapture', 'Check, threat or bigger capture first; the recapture can wait.'),
          wrong('A move that offers a draw', 'Deflection has nothing to do with draw offers.'),
          wrong('A pawn move in the endgame', 'It happens everywhere, but the term means the in-between move, not a pawn move.'),
        ]),
        text(
          'Fire the bodyguard',
          [
            'A defender can guard only one duty at a time. Deflection attacks the defender, forcing it to abandon its post.',
            'The classic form: the enemy rook guards the back rank. You offer your queen on the same rank as the rook. The rook must capture, and now your other rook ends the game on the opened line.',
          ],
          'Attack the guard, not the king. The king falls after.',
        ),
        text(
          'Deflection vs removal',
          [
            'Removal captures the defender outright; deflection chases it off its post. Removal costs material: you give something for the defender. Deflection often costs nothing at all, because the defender must move or be lost.',
            'Ask about every enemy piece: how many jobs does it have? A piece with two jobs can be deflected off either one. A piece with one job must be removed.',
          ],
          'Two jobs: deflect. One job: remove.',
        ),
        demo('Back rank deflection', ['R1d8+ pulls the a8 rook to d8. The second rook recaptures with mate: the back rank never had a second defender.'], 'r5k1/5ppp/8/8/8/8/3R4/3R2K1 w - - 0 1', {
          moves: ['Rd8+', 'Rxd8', 'Rxd8#'],
          caption: 'The rook was bait. The twin rook finished.',
        }),
        drill('Bait the rook', 'r5k1/5ppp/8/8/8/8/3R4/3R2K1 w - - 0 1', ['Rd8+', 'Rxd8', 'Rxd8#'], 'Mate in three by deflecting the a8 rook', 'Offer the d2 rook on d8 with check. The a8 rook must take, and the d1 rook recaptures with mate.', 'Rd8 plus check, rook takes, rook recaptures: mate. This is deflection in its purest form.'),
        quiz('Spotting deflection', 'An enemy rook guards both its king on the back rank and a knight on b2. What is the plan?', [
          right('Attack one duty so hard the rook must abandon the other', 'Deflection wins wherever a piece has two jobs.'),
          wrong('Attack the king directly', 'The rook guards it. Remove the guard first.'),
          wrong('Trade everything off', 'Trading the defender\u2019s enemies helps the defender.'),
        ]),
        quiz('Counting the jobs', 'Which piece is the most likely deflection target in a middlegame?', [
          right('A queen: she usually guards an attack AND defends a key square', 'Queens do everything, which makes them chronically overloaded. Ask what she would hate to stop doing.'),
          wrong('A buried rook on h1', 'Passive pieces often have zero jobs. Nothing to deflect.'),
          wrong('The king in the endgame', 'The king is usually the protected object, not the guard.'),
        ]),
        text(
          'The overload test',
          [
            'When one enemy piece defends two things, ask which job you can make it quit. Deflection works because the guard must choose.',
            'The trick is calculating which job it hates leaving more: if the sacrifice does not win material by force, it is just a gift.',
          ],
          'Every overloaded guard is one deflection away from quitting a job.',
        ),
      ],
    },
    {
      id: 'int-05',
      n: 5,
      title: 'Decoy and clearance',
      subtitle: 'Lure to a doomed square, sweep the road behind you.',
      minutes: 9,
      concepts: ['removingDefender', 'tempo'],
      steps: [
        quiz('Retrieval first', 'What makes deflection different from simple removal of the defender?', [
          right('Deflection chases the defender off its post; removal captures it', 'Chasing can cost nothing. Removal usually trades material for the guard.'),
          wrong('They are the same tactic with different names', 'Different mechanics: one moves the guard, the other deletes it.'),
          wrong('Deflection only works against queens', 'Any overloaded piece can be deflected: rooks above all.'),
        ]),
        text(
          'Two ways to move the enemy',
          [
            'A decoy forces an enemy piece onto a square where a tactic kills it: check the king onto a line, offer a capture onto a fork square.',
            'Clearance is the mirror image with your own pieces: a capture or pawn push empties a square or line so a bigger force can use it. The pawn that captures on f6 and vanishes from the e-file has just opened a rook highway.',
          ],
          'Decoy: pull them in. Clearance: push your own out of the way.',
        ),
        demo('Open the e-file', ['exf6 captures a pawn AND clears the e-file. The rook on e1 now stares at the rook on e8.'], '4r1k1/5p2/5p2/4P3/8/8/8/4R1K1 w - - 0 1', {
          moves: ['exf6', 'Rd8'],
          caption: 'One capture, two jobs: material and an open file',
        }),
        drill('Clear with tempo', '4r1k1/5p2/5p2/4P3/8/8/8/4R1K1 w - - 0 1', ['exf6', 'Rd8'], 'Open the e-file by capturing', 'The pawn takes f6 and stops blocking the rook behind it.', 'exf6. The e-file is open and the pawn attacks g7 as a bonus. Clearance moves that also threaten are gold.'),
        quiz('Decoy target', 'Which square is the classic decoy destination for a king?', [
          right('A square where a knight fork or a mating net is waiting', 'Lure the king to the geometry that kills him.'),
          wrong('The center, always', 'The center is often the safest place for a king in an endgame.'),
          wrong('A defended square', 'A decoy must move the king somewhere WORSE. Defended squares rarely qualify.'),
        ]),
        quiz('Clearance math', 'A clearance capture gives up your pawn (1). Behind it, your rook will win a bishop (3) on the opened line. Was the clearance worth it?', [
          right('Yes: pay 1 to win 3, and the file stays open for more', 'Clearance sacrifices are arithmetic like everything else. Pay less than you collect.'),
          wrong('No: never give up pawns', 'Pawns are the standard currency of clearance. Paying one to open a winning line is profit.'),
          wrong('Only if it is checkmate', 'Winning material or gaining a decisive attack both pay for clearance.'),
        ]),
        playout(
          'Convert the open file',
          'Rook against rook with an open lane. Use the file, hunt loose pawns, win material.',
          '4r1k1/5p2/5p2/4P3/8/8/8/4R1K1 w - - 0 1',
          'w',
          'Win at least 3 points of material within 14 moves',
          2,
          'material',
          14,
          'The open file paid its rent. Files are rook income.',
        ),
      ],
    },
    {
      id: 'int-06',
      n: 6,
      title: 'Outposts and weak squares',
      subtitle: 'Plant a knight where it can never be evicted.',
      minutes: 10,
      concepts: ['outposts', 'pieceActivity'],
      steps: [
        quiz('Retrieval first', 'When is a clearance sacrifice worth playing?', [
          right('When what you win or open is worth more than the piece you move out of the way', 'Pay less than you collect. Same arithmetic as every tactic.'),
          wrong('Never: own pieces must stay put', 'Clearance moves are among the strongest moves in chess when they work.'),
          wrong('Only in the endgame', 'They fire in openings, middlegames and endgames alike.'),
        ]),
        text(
          'A square with a no-eviction notice',
          [
            'An outpost is a square on the enemy half that their pawns can never attack. A knight planted there dominates the board: it attacks pieces without ever being chased.',
            'Weak squares are born from pawn moves. Every pawn push gives up control of two squares forever. When the c- and e-pawns advance, the d5 square becomes a no man\u2019s land.',
          ],
          'Find the square their pawns abandoned. Park a knight there.',
        ),
        demo('The perfect parking spot', ['No black pawn can ever attack e5. The knight travels there for a lifetime appointment.'], 'r1bqk2r/pppp1ppp/8/8/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 6 6', {
          moves: ['Ne5'],
          caption: 'e5: an outpost with a view',
        }),
        demo(
          'The settled knight',
          [
            'The knight has landed. From e5 it watches c6, g6, d7 and f7: four targets, and no black pawn can ever ask it to leave.',
            'Black must spend pieces (not pawns) to challenge it, and every piece that comes to chase is a piece not doing something better. That is what outposts earn.',
          ],
          'r1bqk2r/pppp1ppp/2n5/4N3/2B1P3/8/PPPP1PPP/R1BQK2R w KQkq - 6 6',
          { marks: [{ square: 'e5', color: 'green' }], caption: 'The knight grows a point in value by standing still' },
        ),
        drill('Establish the outpost', 'r1bqk2r/pppp1ppp/8/8/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 6 6', ['Ne5'], 'Plant the knight on the square Black can never attack', 'The c3 knight hops to e5, a square no black pawn can ever attack.', 'Ne5. Untouchable by pawns, attacking c6 and g6. The knight grows a point in value just by standing there.'),
        drill(
          'Anchor it',
          'r1b1k2r/pppp1ppp/8/4N3/2B1P3/8/PPPP1PPP/R1BQK2R w KQkq - 6 6',
          ['f4'],
          'The outpost knight needs a bodyguard. Give him one.',
          'f2-f4 defends the knight on e5 and turns a visit into a residence.',
          'f4. The pawn guards e5, so no enemy piece can trade itself favorably for the knight. An anchored outpost is worth a piece.',
        ),
        quiz('Outpost definition', 'What makes a square an outpost?', [
          right('No enemy pawn can ever attack it, and a piece can safely sit there', 'Pawn-proof squares are real estate. Pieces on them outperform their value.'),
          wrong('Any central square', 'The center matters, but a central square attacked by a pawn is a trap, not an outpost.'),
          wrong('A square next to the enemy king', 'Attack squares matter, but outposts are about permanence.'),
        ]),
        quiz('The best outpost piece', 'Which piece gains the most from an outpost?', [
          right('The knight: short range makes a safe home worth everything', 'A knight on an outpost attacks with no counterplay. Bishops work from a distance and need open lines more than parking spots.'),
          wrong('The queen', 'The queen is strong everywhere. Outposts fix the knight\'s weakness: its short reach.'),
          wrong('The king', 'Kings visit outposts in endgames, but the classic outpost resident is the knight.'),
        ]),
        text(
          'Outposts are built, not found',
          [
            'Outposts appear when pawns disappear. Advance a pawn to drive away a defender, trade the defender off, then plant the knight on the abandoned square.',
            'Strong players plan this three moves ahead: they see the outpost before it exists and build toward it on purpose.',
          ],
          'Trade the guards first, then plant the flag.',
        ),
      ],
    },
    {
      id: 'int-07',
      n: 7,
      title: 'Open files and the 7th rank',
      subtitle: 'Rooks need roads. Give them the best one.',
      minutes: 9,
      concepts: ['openFiles', 'pieceActivity'],
      steps: [
        quiz('Retrieval first', 'Which piece profits most from an outpost square?', [
          right('The knight', 'Short range plus a safe home equals domination.'),
          wrong('The bishop', 'Bishops want open diagonals; the knight wants a parking spot.'),
          wrong('The rook', 'Rooks want files. The outpost is knight country.'),
        ]),
        text(
          'Rook real estate',
          [
            'An open file (no pawns) or half-open file (only enemy pawns) is a rook highway. The first player to occupy it with a rook usually controls the game\u2019s rhythm.',
            'The 7th rank is the prize destination. Two rooks on the 7th eat every enemy pawn and lock the enemy king out of his own camp. Even one rook on the 7th is worth about a pawn on its own.',
          ],
          'Open the file, double the rooks, invade the 7th.',
        ),
        demo('Take the 7th', ['Rook to h7, rook to a7: the entire 7th rank is White\u2019s property.'], '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1', {
          moves: ['Rh7', 'Kd8', 'Raa7'],
          caption: 'Two rooks own the 7th rank',
        }),
        drill('Seize the rank', '4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1', ['Rh7'], 'Invade the 7th rank with a rook', 'The h-file is clear all the way up.', 'Rh7. The rook is deep in enemy territory. The second rook would make it a feast.'),
        drill(
          'Take the half-open file',
          '4k3/5p2/8/8/8/8/8/R3K2R w KQ - 0 1',
          ['Rf1'],
          'Black has a pawn on f7 and you have none on the f-file. Claim the road.',
          'A half-open file is free real estate: only enemy pawns live there.',
          'Rf1. The rook stares down the file at f7, and Black must spend a piece defending a pawn that your rook attacks for free.',
        ),
        quiz('Rook value', 'When does a rook feel like a piece and a half?', [
          right('On an open file, ideally reaching the 7th rank', 'Activity, not the piece itself, decides rook value.'),
          wrong('Behind its own pawns on a closed file', 'That rook is watching a wall.'),
          wrong('Defending a corner', 'Passive rooks lose endgames by themselves.'),
        ]),
        quiz('Half-open file', 'What is a half-open file?', [
          right('A file with only enemy pawns on it: your rook attacks it for free', 'The rook presses the pawn while nothing presses back. It is the cheapest pressure in chess.'),
          wrong('A file with no pawns at all', 'That is a fully open file: even better, but not the question.'),
          wrong('A file blocked by your own pawns', 'That is a closed file: the rook is trapped behind its own army.'),
        ]),
        drill(
          'Seize the file with check',
          '4k3/5ppp/8/8/8/8/8/RR2K3 w - - 0 1',
          ['Ra8+'],
          'Both rooks own the a-file already? No: they own it together. Enter the 8th rank with check',
          'The a-file is clear. Land the leading rook on a8 and the king must react.',
          'Ra8 with check drives the king into the open, where the second rook is already waiting.',
        ),
      ],
    },
    {
      id: 'int-08',
      n: 8,
      title: 'Pawn structure sins',
      subtitle: 'Doubled, isolated, backward: know what you create.',
      minutes: 10,
      concepts: ['pawnStructure', 'outposts'],
      steps: [
        quiz('Retrieval first', 'What does a rook gain from a half-open file?', [
          right('Free attacks on an enemy pawn with nothing attacking back', 'Press the pawn, and every defender it summons is a piece doing nothing else.'),
          wrong('Nothing: rooks prefer closed files', 'Rooks are the pieces that live on files. Closed files starve them.'),
          wrong('It can capture the pawn immediately', 'The pawn is still defended. The file gives pressure, not a free capture.'),
        ]),
        text(
          'Pawns do not go back',
          [
            'Doubled pawns (two on one file) cannot defend each other. Sometimes their open file compensates; usually they are a long-term hangover.',
            'An isolated pawn has no neighbors, so no pawn can ever defend it. It must be guarded by pieces, and the square in front of it becomes an enemy outpost. That is the real cost: the isolani is a target and a parking spot for the opponent.',
            'A backward pawn trails its neighbors and gets parked on. It blocks the file behind it too.',
          ],
          'Every pawn move trades a square for a weakness. Choose consciously.',
        ),
        demo('The isolani problem', ['The black d-pawn is alone. No black pawn can ever defend it, and d5/d6 in front of it is White\u2019s future outpost.'], '4k3/8/8/3p4/8/8/8/R3K3 w - - 0 1', {
          marks: [
            { square: 'd5', color: 'red' },
            { square: 'd6', color: 'yellow' },
          ],
          caption: 'Red: the target. Yellow: the enemy parking lot.',
        }),
        demo(
          'Doubled pawns',
          [
            'Two black pawns on the b-file. They can never shield each other, and the front one is attacked by anything that reaches its file or rank.',
            'The payment: the b-file is now open, so whoever owns a rook there profits. Doubled pawns are a bad deal unless the open file pays rent.',
          ],
          '4k3/8/8/8/8/1p6/1p6/4K3 w - - 0 1',
          { marks: [{ square: 'b3', color: 'red' }, { square: 'b2', color: 'red' }], caption: 'Two pawns, zero mutual defense' },
        ),
        drill('Attack the isolani', '3k4/8/8/3p4/8/8/8/R3K3 w - - 0 1', ['Rd1', 'Kd7'], 'Attack the isolated pawn with the rook', 'The d-file is the direct road: Rd1 hits the pawn at once.', 'Rd1 hits the pawn. Black\u2019s king must baby-sit it forever, and the rook owns the file.'),
        drill(
          'Collect the isolani',
          '3k4/8/8/3p4/8/2N5/8/3RK3 w - - 0 1',
          ['Nxd5'],
          'The knight reaches the isolated pawn. Finish the story.',
          'The c3 knight jumps straight onto d5. Count the defenders first.',
          'Nxd5. The pawn falls AND the knight lands on the very square the isolani used to guard. That is the full punishment for an isolated pawn.',
        ),
        quiz('Weakest structure', 'Which pawn is usually the most enduring weakness?', [
          right('The isolated pawn', 'Nothing can ever defend it with a pawn. Pieces get tied down for the whole game.'),
          wrong('A healthy majority pawn', 'A supported passed pawn is an asset, not a weakness.'),
          wrong('A doubled pawn on an open file', 'It can hurt, but the open file sometimes pays the rent.'),
        ]),
        quiz('The isolani bill', 'When you create an isolated pawn, which side usually gains the better file?', [
          right('The opponent: the file beside the isolani becomes half-open for THEIR rook', 'The pawn cannot be defended by pawns, so rooks pile up. Know the bill before you accept it.'),
          wrong('You: your own file gets stronger', 'Your rook attacks your OWN pawn? The pressure works the other way.'),
          wrong('Nobody: files do not change', 'Captures open files instantly. The isolani always comes with a road for the enemy rook.'),
        ]),
        quiz('Structure or activity?', 'You may choose: keep healthy but passive pawns, or accept an isolated pawn for very active pieces. What is the classic verdict?', [
          right('Activity can fully compensate an isolani, but only if you keep the pieces rolling', 'An isolated pawn is a long-term debt. Active pieces are the income that pays it off.'),
          wrong('Never accept any structural damage for any reason', 'Great players accept isolanis all the time: for space and piece activity.'),
          wrong('Structure always beats activity', 'Static weaknesses only decide when the dynamics are gone. Active pieces fight back.'),
        ]),
      ],
    },
    {
      id: 'int-09',
      n: 9,
      title: 'Good and bad bishops',
      subtitle: 'Same piece, wildly different jobs.',
      minutes: 9,
      concepts: ['bishopPair', 'pawnStructure', 'tradeDecisions'],
      steps: [
        quiz('Retrieval first', 'What is the true cost of an isolated pawn beyond the pawn itself?', [
          right('The square in front of it becomes an enemy outpost', 'The parking spot can outlast the pawn. That square is the real debt.'),
          wrong('Nothing: it is just a weaker pawn', 'The outpost, the half-open file and the tied-down pieces all come with it.'),
          wrong('You lose castling rights', 'Structures and castling are separate matters.'),
        ]),
        text(
          'Ask what the pawns are doing',
          [
            'A bishop is good when its pawns sit on the opposite color, leaving its diagonals open. A bishop is bad when its own pawns block every diagonal it has.',
            'The bishop pair is a long-term bonus: with one bishop of each color you cover the whole board, and the pair often earns a half-point better practical results.',
            'Fixing a bad bishop: trade it, reroute it outside the pawn chain, or unblock the pawns. Letting it rot behind its own wall is how equal endgames are lost.',
          ],
          'Bishop quality = pawn structure. Check the color of your pawns.',
        ),
        demo('The walled-in bishop', ['The light-squared bishop has nothing to do: its own pawns stand on light squares. It is a tall pawn.'], '4k3/8/8/8/8/1p6/1P1B4/4K3 w - - 0 1', {
          marks: [
            { square: 'd2', color: 'red' },
            { square: 'b2', color: 'yellow' },
          ],
          caption: 'Red: the bad bishop. Yellow: its jailer.',
        }),
        drill('Free the prisoner', '4k3/8/8/8/8/1p6/1P1B4/4K3 w - - 0 1', ['Bg5'], 'Activate the bishop to its best diagonal', 'The long dark diagonal is waiting: g5 puts the bishop in the open.', 'Bg5. The bishop is out of jail and eyeing the whole kingside.'),
        drill(
          'Trade the liability',
          '4k3/8/8/8/8/1p2b3/1P1B4/4K3 w - - 0 1',
          ['Bxe3'],
          'The enemy bishop sits on your bad bishop\'s only exit. Solve two problems at once.',
          'Your bishop can reach e3 in one move. What does trading accomplish for both armies?',
          'Bxe3. Your bad bishop leaves, and Black\'s GOOD bishop goes with it. Trading your worst piece for their best is the cheapest fix in positional chess.',
        ),
        quiz('Bishop pair', 'Why is owning both bishops an advantage?', [
          right('Together they cover every square color on the board', 'One of them always has a target: no pawn structure can wall in both at once.'),
          wrong('Two bishops are worth more than a rook', 'Two bishops (6) usually still lose to a rook plus support. The pair is a positional, not material, edge.'),
          wrong('Bishops can jump', 'No piece jumps except the knight.'),
        ]),
        quiz('The bad bishop fix', 'Which of these is NOT a way to fix a bad bishop?', [
          right('Leave it home and hope the pawns move by themselves', 'Pawns never go back. A bad bishop that waits stays bad forever.'),
          wrong('Trade it for an enemy piece', 'Trading the worst piece for any useful enemy piece is a real fix.'),
          wrong('Reroute it outside the pawn chain', 'The classic maneuver: give the jailer the slip and re-enter the game on the other side.'),
        ]),
        quiz('The bishop pair bonus', 'Why do strong players count the bishop pair as worth about half a point extra?', [
          right('Two bishops cover both square colors, so the opponent must answer threats on every shade', 'One bishop can be dodged on the other color. The pair hunts everywhere.'),
          wrong('Bishops are simply always stronger than knights', 'Individually they are equal. The bonus is about the TEAM of two.'),
          wrong('The pair can defend each other like doubled rooks', 'Bishops on opposite colors can never defend each other. The bonus is coverage, not protection.'),
        ]),
      ],
    },
    {
      id: 'int-10',
      n: 10,
      title: 'Practice arena: weapons',
      subtitle: 'Mixed drills from the whole arsenal.',
      minutes: 11,
      concepts: ['doubleAttack', 'discoveredAttack', 'calculation'],
      steps: [
        quiz('Retrieval first', 'How do you fix a bad bishop most cheaply?', [
          right('Trade it for the enemy\'s best piece, or reroute it outside the pawn wall', 'Either the bad bishop leaves or the diagonals open. Both are wins.'),
          wrong('Promote a pawn to get a new bishop', 'There is no new bishop coming. Work with the army you have.'),
          wrong('Trade the pawns instead', 'Some pawn trades wall the bishop in even deeper.'),
        ]),
        text(
          'Everything you own',
          [
            'Five rounds, no new theory. Name the tactic before you move: double attack, discovery, zwischenzug, clearance, skewer.',
            'If one repeats an earlier position, that is the point: retrieval practice is what makes patterns permanent.',
          ],
        ),
        drill('Double attack', '6k1/8/8/r5b1/8/8/8/3QK3 w - - 0 1', ['Qd5+'], 'Hit two pieces with one move', 'Rank 5 is the shared line, and d5 also checks. Ride to d5.', 'Qd5 with check. Same weapon, second rep.'),
        drill('Discovered check', '4k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1', ['Nd6+'], 'Open the e-file with a bang', 'The knight hops to d6, and the rook fires down the e-file.', 'Nd6 plus double check. Unstoppable by definition.'),
        drill('Zwischenzug', 'r1bqkbnr/pppp1ppp/8/4N3/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4', ['Qg5'], 'White\'s knight just grabbed a pawn. Punish the greed in one move.', 'Two targets, one diagonal: the queen lands on g5.', 'Qg5. The trap that eats greedy knights.'),
        drill('Clearance', '4r1k1/5p2/5p2/4P3/8/8/8/4R1K1 w - - 0 1', ['exf6', 'Rd8'], 'Open the line with tempo', 'The e5 pawn takes f6, the e-file opens, and Black\'s rook must leave.', 'exf6. Rook road opened, g7 harassed.'),
        drill(
          'Skewer rep',
          '8/8/8/6kq/8/8/8/R5K1 w - - 0 1',
          ['Ra5+'],
          'King and queen share a rank. One check decides it.',
          'Bring the rook to a5 with check. The king steps, the queen falls.',
          'Ra5 with check, and the queen falls after the king steps. Skewer: the pin in reverse.',
        ),
        playout(
          'Weapons test',
          'Full position, engine opponent. Use everything: forks, discoveries, loose piece hunting.',
          START,
          'w',
          'Win at least 3 points of material within 20 moves',
          3,
          'material',
          20,
          'Arsenal proven. Next: king attacks and endgame technique.',
        ),
      ],
    },
    {
      id: 'int-11',
      n: 11,
      title: 'Attacking the castled king',
      subtitle: 'Storm the walls where they are thinnest.',
      minutes: 10,
      concepts: ['kingSafety', 'pawnBreaks'],
      steps: [
        quiz('Retrieval first', 'What does a clearance sacrifice usually buy?', [
          right('An open line for a bigger piece behind the mover', 'The pawn steps aside and the rook or queen inherits the road.'),
          wrong('A tempo advantage in development', 'Development is a side effect, not the purchase.'),
          wrong('Nothing: it is pure sacrifice', 'It is an investment with a specific return: the line.'),
        ]),
        text(
          'Storms and breakers',
          [
            'A castled king hides behind three pawns. To reach him, march pawns at him or break the wall with pieces. Pawn storms work best when the kings sit on opposite wings. Piece pressure works best against a defense that never finished developing.',
            'The g- and h-pawns lead the storm: g4-g5 chases the f6 knight, the last defender of the kingside. Once the defender moves, the wall has a door.',
            'Every attacking piece should arrive with tempo. An attack with two pieces loses to a defense with four.',
          ],
          'Storm with pawns, break with pieces, arrive with tempo.',
        ),
        demo('The storm gathers', ['h4 and h5 march at the king while the pieces stay flexible. Black must react to the pawn wave.'], 'r1bq1rk1/ppp2ppp/2n5/3p4/3P4/2N2N2/PPP2PPP/R1BQ1RK1 w - - 0 9', {
          moves: ['h4', 'h5'],
          caption: 'The pawn wave rolls forward',
        }),
        drill('Roll the wave', 'r1bq1rk1/ppp2ppp/2n5/3p4/3P4/2N2N2/PPP2PPP/R1BQ1RK1 w - - 0 9', ['h4'], 'Start the kingside storm', 'The h-pawn leads the assault.', 'h4. Every storm starts with a single pawn step. h5 comes next, then the pieces.'),
        drill(
          'Claim the open file',
          'r1bq1rk1/ppp2pp1/2n5/3p4/3P3p/2N2N2/PPP1QPK1/2B1R3 w kq - 0 11',
          ['Rh1'],
          'The h-file is open and the black pawn sits on h4. Put a rook where it hurts.',
          'One of your rooks is one move from the open h-file.',
          'Rh1. The rook stares at h4 and everything behind it. Open files next to the enemy king are attack highways.',
        ),
        quiz('Storm timing', 'A pawn storm works best when...', [
          right('The kings are castled on opposite wings', 'Then your pawn storm races the opponent\u2019s, and whoever opens the wall first usually wins the race.'),
          wrong('Both kings castled on the same side', 'Same-side storms strengthen the enemy wall in front of your own king too. Slow builds are better there.'),
          wrong('You are behind in development', 'Pawns cannot attack alone. Pieces follow the storm.'),
        ]),
        quiz('The last defender', 'Against a castled king, which piece usually must be deflected, traded or driven off before mate ideas work?', [
          right('The knight on f6, the natural guard of the kingside', 'g5 chases it, exchanges remove it, or sacrifices deflect it. No f6 knight, no wall.'),
          wrong('The enemy queen, always', 'The queen is dangerous but rarely the wall. The knight is the classic keeper.'),
          wrong('The h7 pawn itself', 'Pawns are the wall, not the guard. Attack the guards first.'),
        ]),
        text(
          'Storms need closed centers',
          [
            'The classic pawn storm (g4, g5, h4, h5 against a castled king) works when the center is closed: nobody can open lines against your own king while you push.',
            'With an open center, storming pawns open YOUR king first. Check the center before you push a single storm pawn.',
          ],
          'Open center: attack with pieces. Closed center: storm with pawns.',
        ),
      ],
    },
    {
      id: 'int-12',
      n: 12,
      title: 'Defense technique',
      subtitle: 'Trade the attacker, hold the line, hit back.',
      minutes: 10,
      concepts: ['defense', 'tradeDecisions'],
      steps: [
        quiz('Retrieval first', 'Which piece is the classic final defender of a castled kingside?', [
          right('The knight on f6', 'It guards h7 and g8-area squares. Every attack starts by dealing with it.'),
          wrong('The rook on a8', 'It is on the wrong side of the board for kingside defense.'),
          wrong('The h7 pawn', 'The pawn IS the wall. The knight is the guard in front of it.'),
        ]),
        text(
          'Three tools of the defender',
          [
            'Tool one: TRADE the attacker. An attack with one piece is a nuisance; with none, it is nothing. Offer trades whenever the enemy attack has few pieces.',
            'Tool two: CONSOLIDATE. Bring your last piece back to defend, make luft, guard the weak square. Boring moves save games.',
            'Tool three: COUNTERATTACK. If their attack ignores your threats, hit somewhere else. Defense does not mean waiting; it means spending tempo where it counts.',
          ],
          'Trade, consolidate, counter. In that order of desperation.',
        ),
        drill('Trade the attacker', '4k3/8/8/8/8/2r5/8/2R1K3 w - - 0 1', ['Rxc3'], 'The black rook is the attacker. Remove it.', 'Two rooks share the c-file. Take on c3, and the attack is gone.', 'Rxc3. The attack is gone. Defense by simplification.'),
        drill('Counterattack', '4k3/8/8/8/R2q4/8/8/4K3 w - - 0 1', ['Rxd4'], 'Your rook on a4 is attacked by the queen. Answer with force.', 'The queen on d4 is undefended. Your rook on a4 sees her along the rank.', 'Rxd4. The best defense here is a capture. Nine points of attacker, gone.'),
        quiz('Defensive trade', 'You are under attack by a queen and a knight. What is the best defensive move usually?', [
          right('Offer a trade of one of the attackers', 'Each trade shrinks the attack until it is harmless.'),
          wrong('Push more pawns', 'Pawns do not defend an attack. They open lines for it.'),
          wrong('Ignore it and attack too', 'Sometimes right, but only when your counterattack comes first. Otherwise trade.'),
        ]),
        quiz('Luft under fire', 'You are being attacked. Should you spend a move making luft (h3 or g3)?', [
          right('Only when back-rank tricks are the actual threat', 'Every tempo under attack is precious. Luft buys safety only if the back rank is where the attack lands.'),
          wrong('Always: luft comes first', 'A pointless luft move under attack can be the losing tempo.'),
          wrong('Never while attacked', 'When the attacker threatens Re8-style mate, luft IS the defensive move. Judge by the threat.'),
        ]),
      ],
    },
    {
      id: 'int-13',
      n: 13,
      title: 'Two weaknesses',
      subtitle: 'One defense can hold. Two collapse.',
      minutes: 10,
      concepts: ['initiative', 'pieceActivity'],
      steps: [
        quiz('Retrieval first', 'When should the defender spend a tempo on luft?', [
          right('When the back rank itself is the threatened entry', 'Luft is defense only where it answers the real threat.'),
          wrong('Before every game', 'Luft is situational, not a ritual.'),
          wrong('When short of time', 'Time trouble is exactly when automatic ritual moves go wrong.'),
        ]),
        text(
          'Stretch the defense',
          [
            'A single weakness is easy to guard: park a piece nearby and it is safe forever. Two weaknesses on opposite wings are deadly, because the defense cannot be in two places.',
            'When your main attack stalls, do not push harder against the same wall. Open a second front: a pawn break on the other side, a knight jumping to a new outpost, a rook invasion on a fresh file.',
          ],
          'One front is a fight. Two fronts are a win.',
        ),
        demo('Two fronts', ['The d5 pawn is a target on one side; the h5 pawn is a second target far away. The black pieces cannot guard both roads.'], '4k3/8/8/2pp4/8/8/8/R3K3 w - - 0 1', {
          marks: [
            { square: 'd5', color: 'red' },
            { square: 'h5', color: 'yellow' },
          ],
          caption: 'Red and yellow: the defense must split',
        }),
        drill(
          'Open the far front',
          '4k3/1p6/8/8/8/8/8/R3K3 w - - 0 1',
          ['Ra7'],
          'One army, one far-away target. Start pressure where the defense is thin.',
          'The a-file runs straight to Black\u2019s home rank. The 7th is the destination.',
          'Ra7. The far corner becomes a second problem. Distance is the weapon: pieces cannot defend two continents.',
        ),
        quiz('Creating the second front', 'Your kingside attack has stalled. Where does the second weakness usually come from?', [
          right('A pawn break or invasion on the opposite side of the board', 'Distance is the whole weapon: the defense cannot teleport.'),
          wrong('Doubling pieces behind the same pawn', 'More force against one weakness still loses to one defender.'),
          wrong('Trading queens', 'Fewer pieces means fewer attacking options. Sometimes right in endgames, rarely in an attack.'),
        ]),
        quiz('Which weakness first?', 'You have created weaknesses on both wings. Which do you attack?', [
          right('The one whose defense forces the longest trip for the enemy pieces', 'Attack where help is farthest away. Geometry decides.'),
          wrong('Always the nearest one to your pieces', 'Near is convenient, but the far weakness stretches the defense further.'),
          wrong('The most valuable piece, always', 'Value matters less than whether the defense can arrive in time.'),
        ]),
        playout(
          'Fight on two fronts',
          'Win material by using more than one threat. When one door closes, knock on another.',
          START,
          'w',
          'Win at least 3 points of material within 20 moves',
          3,
          'material',
          20,
          'Two fronts, one win. That is intermediate chess.',
        ),
      ],
    },
    {
      id: 'int-14',
      n: 14,
      title: 'King activity and opposition',
      subtitle: 'In the endgame, the king is a fighting piece.',
      minutes: 10,
      concepts: ['kingActivity', 'opposition', 'endgame'],
      steps: [
        quiz('Retrieval first', 'How do you choose which of two weaknesses to attack?', [
          right('The one the enemy pieces reach last', 'Distance is defense. Attack where the help is late.'),
          wrong('Always the closest target', 'The closest target is also the best defended.'),
          wrong('Coin flip', 'Geometry gives the answer every time.'),
        ]),
        text(
          'The king walks out',
          [
            'Once the queens are off, the king marches to the center. In endgames, king activity is worth more than a pawn in most positions.',
            'Opposition: when the kings face each other with exactly one square between them, the side not to move owns the crossing squares. Win the opposition, and your pawn walks through.',
          ],
          'Centralize the king, win the opposition, promote the pawn.',
        ),
        demo('Face to face', ['The kings stand in direct opposition on the e-file. Whoever must move steps aside, and the pawn escorts his king through.'], '8/8/8/4k3/8/4K3/4P3/8 w - - 0 1', {
          marks: [
            { square: 'e5', color: 'red' },
            { square: 'e3', color: 'green' },
          ],
          caption: 'Direct opposition: one square between',
        }),
        drill('Take the opposition', '8/8/8/3k4/8/8/3K4/8 w - - 0 1', ['Kd3'], 'Face the black king with one square between', 'The d-file connects the kings. Kd3 faces him with one square between.', 'Kd3. Direct opposition. If Black steps aside, your king eats the key squares.'),
        drill(
          'Escort with opposition',
          '8/8/8/4k3/8/4K3/4P3/8 w - - 0 1',
          ['Kd3'],
          'Gain space with the king while keeping the pawn safe',
          'Step aside to d3: the pawn stays protected, and the kings keep their duel.',
          'Kd3. Black must choose between opposition and space, and both choices lose the key squares. King dances win pawn endings.',
        ),
        quiz('Opposition rule', 'Kings face each other with one square between. Who is in control?', [
          right('The side not to move', 'The side to move must give way. The other side owns the opposition.'),
          wrong('The side to move', 'Moving is exactly the problem: you must step aside first.'),
          wrong('Nobody, kings are equal', 'The turn decides everything in king duels.'),
        ]),
        quiz('King target squares', 'In a king-and-pawn race, which squares does the attacking king head for?', [
          right('The squares directly in front of the pawn', 'The king escorts: in front of the pawn is where he controls the promotion path.'),
          wrong('The corner where the enemy king sits', 'Corner trips waste time. The pawn\'s path is the highway.'),
          wrong('His own first rank', 'A defensive king loses pawn endings. March forward.'),
        ]),
        quiz('The turn decides', 'In king-and-pawn endings, why does whose turn it is matter so much?', [
          right('Kings cannot wait in place: the side to move must often give ground first', 'Two kings facing each other create a waiting problem. Whoever must move, loses ground.'),
          wrong('Because pawn moves are always forced', 'Pawns usually have choices. The kings are the ones running out of moves.'),
          wrong('The turn only matters when rooks are on the board', 'The turn decides pure king duels. Rooks make it messier, not more important.'),
        ]),
      ],
    },
    {
      id: 'int-15',
      n: 15,
      title: 'Pawn endings',
      subtitle: 'The square rule and the pawn race.',
      minutes: 10,
      concepts: ['endgame', 'technique'],
      steps: [
        quiz('Retrieval first', 'Where does the attacking king go in a king-and-pawn endgame?', [
          right('In front of his own pawn', 'The escort formation. The pawn is only as strong as the king driving it.'),
          wrong('Behind the pawn', 'A king behind its pawn is a bodyguard for yesterday.'),
          wrong('Toward the enemy king only', 'The king helps the pawn first; the duel happens on the way.'),
        ]),
        text(
          'Geometry of the runner',
          [
            'The square rule: a pawn that starts running can be caught only if the defending king can step into its square, the box from the pawn to its promotion square. Inside the square: catch it. Outside: it queens.',
            'In pawn races, count tempi before anything else. One tempo decides whether the race is won, lost, or drawn by the first player promoting and then stopping the other pawn.',
          ],
          'Draw the square in your head before every king move.',
        ),
        demo('The square', ['The black pawn on d5 runs to d1. The gold square is its escape box. A king outside cannot catch it; a king inside always can.'], '8/8/8/3p4/8/8/6K1/7k w - - 0 1', {
          marks: [
            { square: 'd1', color: 'gold' },
            { square: 'd2', color: 'gold' },
            { square: 'd3', color: 'gold' },
            { square: 'd4', color: 'gold' },
          ],
          caption: 'The square of the pawn',
        }),
        drill('Catch the runner', '8/8/8/3p4/8/8/6K1/7k w - - 0 1', ['Kf3'], 'Step into the square and stop the pawn', 'The king on g2 is outside the box. Kf3 steps inside it.', 'Kf3. Inside the square now. The pawn cannot run away from you anymore.'),
        drill(
          'Sit in the square',
          '6k1/8/8/7p/8/7K/8/8 w - - 0 1',
          ['Kh4'],
          'The black h-pawn is thinking about running. End the discussion.',
          'The king is already inside the square. Kh4 parks on the pawn\'s file, and the pawn is stuck forever.',
          'Kh4. The pawn cannot advance past a king parked on its file. Being inside the square is a lifetime pass.',
        ),
        quiz('Square rule', 'A black pawn on a5 runs to a1. The white king stands on e4. Can he catch it?', [
          right('Yes, e4 is inside the square of the a5 pawn', 'The square reaches from a5 down to a1 and across to e4. The king is inside, so he catches the pawn.'),
          wrong('No, the pawn is too fast', 'Distance from e4 to a1 is 3 moves; the pawn needs 4. The king wins the race.'),
          wrong('Only with the white king on e3', 'e4 already works. The square rule is generous to the side with the better king position.'),
        ]),
        quiz('The move in the square rule', 'Does it matter whose move it is when applying the square rule?', [
          right('Yes: if the defender moves first and can enter the square this move, he catches the pawn', 'The rule assumes it is the pawn\'s move. If the king moves first, he gets a free step into the box.'),
          wrong('No: the square rule ignores the turn', 'The turn is exactly what the rule measures. King-first changes the verdict.'),
          wrong('Only in queen endings', 'The square rule is a king-and-pawn tool, and the turn is part of it.'),
        ]),
        quiz('Racing math', 'Your pawn runs for the last rank while the enemy king is far away. What exactly do you check?', [
          right('Whether the enemy king can step inside the square of the pawn', 'Inside the square means the king catches it. Outside means the pawn promotes.'),
          wrong('The total number of pawns left on the board', 'Pawn counts do not stop runners. Geometry does.'),
          wrong('Whether the enemy rook is active', 'There is no rook in a pure pawn race. The king and the square are the whole story.'),
        ]),
      ],
    },
    {
      id: 'int-16',
      n: 16,
      title: 'Rook endings basics',
      subtitle: 'Cut the king off, keep the rook active.',
      minutes: 10,
      concepts: ['endgame', 'pieceActivity'],
      steps: [
        quiz('Retrieval first', 'When the defender moves first, how does the square rule change?', [
          right('He gets a free step: entering the square this move catches the pawn', 'The standard rule assumes the pawn moves first. King-first adds one tempo of reach.'),
          wrong('It does not change anything', 'The turn is half the rule.'),
          wrong('The pawn gets faster', 'Pawns always step one square. The king\'s first move is the variable.'),
        ]),
        text(
          'The active rook wins',
          [
            'In rook endgames the attacking rook belongs behind a passed pawn, yours or theirs. Behind your own pawn it escorts the pawn. Behind theirs it attacks the pawn from a square the pawn can never fight back from.',
            'Cutting off: park the rook on a rank or file in front of the enemy king and he is locked out of the game. A cut-off king cannot defend pawns or fight for promotion squares.',
          ],
          'Rook behind the pawn, king out of the game.',
        ),
        demo('The wall goes up', ['Ra5 draws a line across the 5th rank. The black king on h8 can never cross it while the rook patrols.'], '7k/8/8/8/8/8/8/R3K3 w - - 0 1', {
          moves: ['Ra5'],
          caption: 'The king is cut off from the lower ranks',
        }),
        drill('Build the wall', '7k/8/8/8/8/8/8/R3K3 w - - 0 1', ['Ra5'], 'Cut the black king off with the rook', 'The 5th rank is the fence: Ra5 locks the king on the 8th.', 'Ra5. The king is a spectator now. Your own king walks in freely and takes over.'),
        quiz('Rook placement', 'Where does the attacking rook belong relative to a passed pawn?', [
          right('Behind it, whoever the pawn belongs to', 'Behind your pawn it escorts. Behind theirs it herds.'),
          wrong('In front of it, blocking', 'A rook in front of its own pawn blocks it. In front of theirs, it gets attacked by the king.'),
          wrong('On the first rank, defending', 'Passive rooks lose rook endgames. Activity is the whole story.'),
        ]),
        quiz('Behind your own passer', 'Your rook sits behind your own passed pawn. What does it do from there?', [
          right('Pushes: every pawn step is protected by the rook from behind', 'The rook clears the road ahead and the pawn walks to promotion.'),
          wrong('Blocks the pawn from moving', 'Blocking your own passer is the job of the ENEMY. Yours pushes.'),
          wrong('Rushes to attack the king instead', 'A rook that abandons the passer usually abandons the win.'),
        ]),
        quiz('Cut-off distance', 'Which rank best cuts off an enemy king?', [
          right('Far enough in front of him that the rook can never be attacked', 'Two or three ranks of distance: close enough to matter, far enough to be safe.'),
          wrong('The rank directly in front of the king', 'Too close: the king attacks the rook and breaks the fence.'),
          wrong('Always the first rank', 'Passive first-rank rooks defend nothing and cut off nobody.'),
        ]),
      ],
    },
    {
      id: 'int-17',
      n: 17,
      title: 'Converting an advantage',
      subtitle: 'Winning won positions is its own skill.',
      minutes: 10,
      concepts: ['technique', 'tradeDecisions', 'endgame'],
      steps: [
        quiz('Retrieval first', 'How far from the enemy king should a cut-off rook stand?', [
          right('Two or three ranks: close enough to matter, far enough to be safe', 'A fence the king can attack is not a fence.'),
          wrong('Right in front of him', 'The king captures or attacks a rook that comes too close.'),
          wrong('Distance does not matter', 'Distance is exactly what keeps the rook active instead of dead.'),
        ]),
        text(
          'Trade pieces, keep tension',
          [
            'When you are up material, trade PIECES, not pawns. Fewer enemy pieces means less counterplay; keeping pawns means more winning chances later.',
            'Kill counterplay first. Ask every move: what does my opponent want? Deny it, then improve your worst piece. Technique is patience with a plan.',
            'The king joins the attack in the endgame. Centralize him, escort the passed pawn, and the point takes care of itself.',
          ],
          'Simplify pieces, multiply pawns, deactivate their plans.',
        ),
        demo('Rook and king finish it', ['Up a rook, the win is technique: rook cuts the king, your king approaches, mate follows.'], '7k/8/8/8/8/8/8/R3K3 w - - 0 1', {
          marks: [{ square: 'a5', color: 'green' }],
          caption: 'Ra5 first, then the king walks up',
        }),
        quiz('Conversion rule', 'You are up a whole rook in a middlegame. What do you trade?', [
          right('Pieces, not pawns', 'Fewer enemy pieces means less counterplay. Pawns are your winning margin.'),
          wrong('Pawns, not pieces', 'Trading pawns opens lines for the enemy pieces to swarm you.'),
          wrong('Nothing, sit on the material', 'Passive defense invites attacks. Simplify and activate.'),
        ]),
        quiz('The first conversion question', 'You just won a piece. What is the first question on every following move?', [
          right('What does my opponent want, and how do I deny it?', 'Counterplay dies first. Then the technique plays itself.'),
          wrong('Where can I attack the king?', 'Attacking while ahead is how won games get mated. Deny first.'),
          wrong('How do I win even more material?', 'Greed extends the game. Converting means closing doors, not opening them.'),
        ]),
        playout(
          'Technique test',
          'Rook against a lone king: the classic conversion. Box the king with the rook, bring your king, mate.',
          '7k/8/8/8/8/8/8/R3K3 w - - 0 1',
          'w',
          'Checkmate the black king',
          1,
          'checkmate',
          25,
          'Converted. Rook mate is the first technique every tournament player owns.',
          'Reset and try the ladder: rook cuts a rank, your king approaches, repeat. Never let the king touch your rook.',
        ),
      ],
    },
    {
      id: 'int-18',
      n: 18,
      title: 'Practice arena: endgames',
      subtitle: 'Kings, pawns and rooks under pressure.',
      minutes: 11,
      concepts: ['endgame', 'kingActivity', 'promotion'],
      steps: [
        quiz('Retrieval first', 'What is the first question when converting a won position?', [
          right('What does my opponent want, and how do I deny it?', 'Counterplay first, technique second. That order wins games.'),
          wrong('How do I attack faster?', 'Attacks while ahead are how wins become draws.'),
          wrong('Which pieces can I hoard?', 'Holding everything invites one big tactic. Simplify on purpose.'),
        ]),
        text(
          'Endgame reps',
          [
            'Four drills from the endgame levels, then a playable pawn ending.',
            'In every drill, ask about the kings first. Endgames are king duels with pawns as the stakes.',
          ],
        ),
        drill('Opposition rep', '8/8/8/3k4/8/8/3K4/8 w - - 0 1', ['Kd3'], 'Take the direct opposition', 'One square between the kings: Kd3 faces him on the d-file.', 'Kd3. The opposition is yours.'),
        drill('Square rule rep', '8/8/8/3p4/8/8/6K1/7k w - - 0 1', ['Kf3'], 'Catch the running pawn', 'Kf3 steps inside the square.', 'Kf3. Caught. Geometry beats hope.'),
        drill('Cut off rep', '7k/8/8/8/8/8/8/R3K3 w - - 0 1', ['Ra5'], 'Fence the king out', 'The 5th rank is the wall: Ra5.', 'Ra5. The wall holds.'),
        drill(
          'Promote with tempo rep',
          '4k3/6P1/8/8/8/8/8/4K3 w - - 0 1',
          ['g8=Q+'],
          'The passer promotes. Land with a check.',
          'The new queen fires down the 8th rank the instant she appears.',
          'g8=Q with check. Promoting with tempo means Black answers you instead of counterattacking.',
        ),
        quiz('King priority check', 'Kings and pawns only. Your first question every move is about...', [
          right('King position: activity and opposition', 'The king is the strongest piece in pawn endings.'),
          wrong('Pawn storms at the enemy king', 'There is no attack without pieces. The king walks, not storms.'),
          wrong('Rook activity', 'No rooks on the board in a pawn ending.'),
        ]),
        playout(
          'Pawn ending duel',
          'King and pawn against a lone king. Push the pawn with the king in front. Win material or promote.',
          '8/8/8/3k4/8/3K4/4P3/8 w - - 0 1',
          'w',
          'Win the pawn race or promote within 15 moves',
          2,
          'material',
          15,
          'King activity, opposition, promotion: the full pawn-ending method in one game.',
        ),
      ],
    },
    {
      id: 'int-19',
      n: 19,
      title: 'Practice arena: mixed',
      subtitle: 'Tactics and technique, shuffled.',
      minutes: 11,
      concepts: ['calculation', 'winningMaterial'],
      steps: [
        quiz('Retrieval first', 'Which promoting move is usually strongest: plain promotion or promotion with check?', [
          right('Promotion with check: Black must answer instead of counterattacking', 'Tempo on the promotion square is worth almost a move.'),
          wrong('Plain promotion: checks waste the pawn', 'Checks are free. Take them when they land.'),
          wrong('It never matters', 'The tempo decides races and attacks constantly.'),
        ]),
        text(
          'Interleaving test',
          [
            'Mixed reps: you will not be told which skill each drill needs. Recognizing which tool applies is the actual skill.',
            'Scan order: checks first, then captures, then threats.',
          ],
        ),
        drill('Unknown 1', '6k1/8/8/r5b1/8/8/8/3QK3 w - - 0 1', ['Qd5+'], 'White to move: find the strong move', 'Two black pieces share rank 5, and d5 also checks the king.', 'Qd5 with check. Double attack.'),
        drill('Unknown 2', '4k3/8/8/8/R2q4/8/8/4K3 w - - 0 1', ['Rxd4'], 'White to move: deal with the queen', 'The rook is attacked. So is she.', 'Rxd4. Counterattack by capture.'),
        drill('Unknown 3', 'r1bqkbnr/pppp1ppp/8/4N3/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4', ['Qg5'], 'Black to move: White\'s knight sits on e5, loose and greedy. Find the punishing move.', 'Is there something better than recapturing?', 'Qg5. The zwischenzug strikes again.'),
        drill(
          'Unknown 4',
          '8/8/8/6kq/8/8/8/R5K1 w - - 0 1',
          ['Ra5+'],
          'White to move: one line decides everything',
          'Two black pieces share the 5th rank, and one of them is the king.',
          'Ra5 with check: the skewer. The king steps and the queen falls.',
        ),
        playout(
          'Final mixed game',
          'Everything you have learned in one game.',
          START,
          'w',
          'Win at least 3 points of material within 20 moves',
          4,
          'material',
          20,
          'Intermediate tier nearly done. One level left.',
        ),
      ],
    },
    {
      id: 'int-20',
      n: 20,
      title: 'Intermediate graduation',
      subtitle: 'A famous pattern, one exam, one game.',
      minutes: 14,
      concepts: ['famousGame', 'mate', 'sacrifice'],
      steps: [
        text(
          'The exam',
          [
            'Before the final quiz, play through the most famous mating pattern in chess history: a knight checks, the queen gives herself away, and the king is buried by his own army.',
            'Then three questions and a full game against a stronger engine.',
          ],
          'Pass the quiz, play the pattern, win the game.',
        ),
        gtmStep(
          'The smothered mate pattern',
          [
            'The most famous finish in chess needs no introduction: a knight checks, a queen sacrifices itself, and the king is buried by its own pieces. Philidor wrote the pattern down in 1749 and it has decided thousands of games since.',
            'You play White. Find the four moves of the pattern in order. Three of them give check, one is a double check, the queen move is a sacrifice Black is forced to accept, and the last one is mate.',
          ],
          'The classic smothered mate pattern, after Philidor',
          '5r1k/6pp/8/6N1/8/1Q6/8/6K1 w - - 0 1',
          [],
          [
            guess('Nf7+', 'The knight dives in with check, driving the king to the only square where the pattern works.', { reply: 'Kg8' }),
            guess('Nh6+', 'Double check: the knight attacks g8 and the queen on b3 now looks down the long diagonal at it too. Double check always forces the king to move, and h8 is the only square.', { reply: 'Kh8' }),
            guess('Qg8+', 'The queen offers itself so Black\u2019s own rook must capture and smother its own king. There is no other way to make progress.', { reply: 'Rxg8' }),
            guess('Nf7#', 'The smothered mate: the king on h8 is boxed in by its own rook and pawns, and the knight lands protected and unanswerable.'),
          ],
        ),
        quiz('Tool selection', 'Your opponent recaptured a piece and left his queen hanging to a knight fork. You were thinking about your own recapture. What saved you?', [
          right('Running the scan: checks, captures, threats, every move', 'The scan finds forks before they cost material.'),
          wrong('Luck', 'Not a strategy.'),
          wrong('Deep opening preparation', 'The fork happens on move 30, not move 10.'),
        ]),
        quiz('The smothered idea', 'Why does the queen sacrifice on g8 work at all?', [
          right('The rook must capture, and its own rook then smothers the king', 'The rook has no choice: it lands on g8, the king\'s last escape square. The knight then mates on f7, protected by its twin on h6.'),
          wrong('The queen was trapped and lost anyway', 'The queen had many squares. The sacrifice was the fastest road to mate.'),
          wrong('Because the knight on h6 protects g8', 'The knight protects f7, its landing square. The g8 rook is the real smotherer.'),
        ]),
        quiz('Endgame priority', 'Kings and pawns only. Your first priority every move is...', [
          right('King position: activity and opposition', 'The king is the strongest piece in pawn endings.'),
          wrong('Pawn storms at the enemy king', 'There is no attack without pieces. The king walks, not storms.'),
          wrong('Rook activity', 'No rooks on the board in a pawn ending.'),
        ]),
        playout(
          'Graduation game',
          'Beat the level 4 engine on material within 20 moves.',
          START,
          'w',
          'Win 3 or more points of material within 20 moves',
          4,
          'material',
          20,
          'Intermediate tier cleared. Advanced tier awaits.',
        ),
      ],
    },
  ],
}
