import type { Level } from '../schema'

export const level1: Level = {
  id: 'first-moves',
  n: 1,
  title: 'First Moves',
  tagline: 'The board, the pieces, and the moves that end games.',
  color: '#7fa650',
  lessons: [
    {
      id: 'how-pieces-move',
      title: 'How the pieces move',
      subtitle: 'Six pieces, six personalities. Learn what each one can do.',
      minutes: 12,
      steps: [
        {
          type: 'text',
          title: 'The board',
          body: [
            'The board is 8 columns (files a–h) by 8 rows (ranks 1–8). Every square has a name: the file letter first, then the rank number.',
            'White starts on ranks 1 and 2. Black starts on ranks 7 and 8. The bottom-right square from White\'s side is always a light one — if it isn\'t, the board is turned around.',
            'When you read chess notation, "Nf3" means the knight moved to f3. Once you can name squares, you can read any chess book, watch any stream, and follow any game.',
          ],
          keyIdea: 'Files run a–h, ranks run 1–8. Square name = file + rank, like e4.',
        },
        {
          type: 'demo',
          title: 'Naming squares',
          body: [
            'A few key squares worth knowing by heart: e4 and d4 are the center squares White fights for first; e5 and d5 are Black\'s.',
            'f7 and f2 are the weak spots in front of each king — remember them, they decide a lot of games.',
          ],
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          marks: [
            { square: 'e4', color: 'green' },
            { square: 'd4', color: 'green' },
            { square: 'e5', color: 'red' },
            { square: 'd5', color: 'red' },
            { square: 'f7', color: 'yellow' },
            { square: 'f2', color: 'yellow' },
          ],
          caption: 'The starting position',
        },
        {
          type: 'demo',
          title: 'Pawns: forward only',
          body: [
            'Pawns move one square straight ahead. From their starting square they may move two.',
            'They capture diagonally — one square forward-left or forward-right — and they can never move backward.',
          ],
          fen: '4k3/8/8/8/8/8/4P3/4K3 w - - 0 1',
          moves: ['e4'],
          caption: 'White plays the two-square push',
        },
        {
          type: 'demo',
          title: 'Pawns: capture diagonally',
          body: [
            'Same pawn, now on e4. The black pawn on d5 is one square diagonally ahead — that means it can be taken.',
            'Pawns are the only pieces that move one way and capture another.',
          ],
          fen: '4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1',
          moves: ['exd5'],
          caption: 'exd5 — the pawn takes diagonally',
        },
        {
          type: 'exercise',
          title: 'Take the pawn',
          body: ['A black pawn has stepped onto d5, right in front of yours. Collect it.'],
          fen: '4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1',
          solution: ['exd5'],
          goal: 'Capture the pawn on d5',
          hint: 'Pawns capture one square diagonally forward. Your pawn is on e4.',
          success: 'Exactly. You just won a pawn.',
        },
        {
          type: 'quiz',
          title: 'Pawn capture quiz',
          question: 'A white pawn sits on e4. Which squares can it capture on?',
          options: [
            { text: 'd5 and f5', correct: true, why: 'One square diagonally forward — that is the only way pawns capture.' },
            { text: 'd4 and f4', why: 'd4 and f4 are sideways. Pawns never capture sideways.' },
            { text: 'e5 only', why: 'e5 is where it moves — but captures are diagonal, not straight ahead.' },
          ],
        },
        {
          type: 'demo',
          title: 'Knights: the jumpers',
          body: [
            'The knight moves in an L: two squares one way, then one square sideways. It is the only piece that can jump over anything in its path.',
            'A knight in the center attacks up to 8 squares; on the edge it attacks 4 or fewer. Keep knights centralized.',
          ],
          fen: '4k3/8/8/8/3N4/8/8/4K3 w - - 0 1',
          moves: ['Nc6'],
          caption: 'The L-shaped hop, right over the pawn wall',
        },
        {
          type: 'exercise',
          title: 'Jump the wall',
          body: [
            'The pawns on e3 and g3 wall off the diagonal — any bishop would be stuck behind them.',
            'The knight does not care. Jump over the wall and take the pawn on f5.',
          ],
          fen: '4k3/8/8/5p2/3N4/4p1p1/8/4K3 w - - 0 1',
          solution: ['Nxf5'],
          goal: 'Capture the pawn on f5',
          hint: 'Two up, one across: from d4, think of the squares an L-shape reaches.',
          success: 'Over the wall. That is exactly why knights are awkward to trap.',
        },
        {
          type: 'quiz',
          title: 'Which piece jumps?',
          question: 'Which is the only piece that can jump over other pieces?',
          options: [
            { text: 'The knight', correct: true, why: 'Only the knight ignores blockers on its way to its destination square.' },
            { text: 'The bishop', why: 'Bishops slide along clear diagonals. Any piece in the way stops them.' },
            { text: 'The queen', why: 'The queen slides along clear lines too. Blockers stop her.' },
          ],
        },
        {
          type: 'demo',
          title: 'Bishops: diagonals forever',
          body: [
            'Bishops slide any distance along diagonals. One bishop lives on light squares its whole life, the other on dark squares.',
            'A bishop on a blocked diagonal is a tall pawn. Open diagonals are what make bishops strong.',
          ],
          fen: '4k3/8/8/8/3B4/8/8/4K3 w - - 0 1',
          moves: ['Bg7'],
          caption: 'd4 to g7 — one long diagonal',
        },
        {
          type: 'quiz',
          title: 'Same color forever',
          question: 'A bishop starts on f1. Which square can it NEVER reach?',
          options: [
            { text: 'd3', why: 'd3 is a light square, same color as f1. Reachable.' },
            { text: 'e5', correct: true, why: 'e5 is a dark square. A bishop that starts on light squares stays on them forever.' },
            { text: 'g2', why: 'g2 is light. Same color as f1, so it can get there.' },
          ],
        },
        {
          type: 'demo',
          title: 'Rooks: ranks and files',
          body: [
            'Rooks slide along ranks and files — straight lines only. They love open files and the 7th rank.',
            'In the starting position the rooks are the hardest pieces to develop. That is why you castle: it connects them.',
          ],
          fen: '8/8/8/4k3/8/8/8/R3K3 w - - 0 1',
          moves: ['Ra8'],
          caption: 'One move, the whole file',
        },
        {
          type: 'demo',
          title: 'Queen: rook + bishop',
          body: [
            'The queen moves like a rook and a bishop combined — any number of squares in any straight direction. She is worth about 9 pawns, more than two rooks.',
            'Bring her out too early, though, and she gets chased around while your opponent develops for free.',
          ],
          fen: '8/8/8/4k3/8/8/8/Q3K3 w - - 0 1',
          moves: ['Qa8'],
          caption: 'Rank and file — the queen does both',
        },
        {
          type: 'demo',
          title: 'King: one square at a time',
          body: [
            'The king moves one square in any direction — but never onto a square attacked by the enemy.',
            'He is slow in the opening, and decisive in the endgame. Once the queens are off, an active king wins games.',
          ],
          fen: '4k3/8/8/8/8/8/8/4K3 w - - 0 1',
          moves: ['Kd1'],
          caption: 'One careful step',
        },
        {
          type: 'quiz',
          title: 'Piece values',
          question: 'Roughly how many pawns is a knight or bishop worth?',
          options: [
            { text: 'About 3', correct: true, why: 'Minor pieces are worth ~3 pawns, rooks ~5, the queen ~9. Values guide trades.' },
            { text: 'About 5', why: '5 is a rook. Knights and bishops are a step below.' },
            { text: 'About 1', why: 'That is a pawn. Minor pieces are far stronger.' },
          ],
        },
        {
          type: 'quiz',
          title: 'The strongest piece',
          question: 'Which piece is worth the most?',
          options: [
            { text: 'The queen', correct: true, why: 'About 9 pawns. Losing her for nothing usually loses the game.' },
            { text: 'The rook', why: 'A rook is strong (~5) but the queen out-values it.' },
            { text: 'The king', why: 'The king is priceless — but he is not counted in trades, and he never gets captured.' },
          ],
        },
      ],
    },
    {
      id: 'special-moves',
      title: 'Special moves & rules',
      subtitle: 'Castling, en passant, promotion — and the ways games end in a draw.',
      minutes: 12,
      steps: [
        {
          type: 'text',
          title: 'Castling',
          body: [
            'Once per game, the king and a rook can move together. King two squares toward the rook, rook hops over: that is castling.',
            'Four conditions must ALL hold: neither king nor rook has moved; no pieces stand between them; the king is not in check; and the king does not pass through or land on an attacked square.',
            'Castling does two jobs at once: it hides the king behind a pawn wall and brings a rook toward the center.',
          ],
          keyIdea: 'Castle early. A king stuck in the center loses games.',
        },
        {
          type: 'demo',
          title: 'Castling kingside',
          body: [
            'Both sides have kept the squares between king and rook clear. White plays 0-0: king e1 to g1, rook h1 to f1.',
          ],
          fen: 'r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',
          moves: ['O-O'],
          caption: 'Short castling',
        },
        {
          type: 'demo',
          title: 'Castling queenside',
          body: [
            'The long way: 0-0-0 sends the king from e1 to c1, with the a1 rook landing on d1. Three squares between king and rook must be empty.',
          ],
          fen: 'r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',
          moves: ['O-O-O'],
          caption: 'Long castling',
        },
        {
          type: 'exercise',
          title: 'Castle now',
          body: [
            'This is a natural position from the Italian Game. White\'s king still sits in the middle — get him to safety.',
          ],
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
          solution: ['O-O'],
          goal: 'Castle kingside',
          hint: 'f1 and g1 are empty and nothing attacks them. Make the two-piece move.',
          success: 'King safe, rook active. This is what a good opening move looks like.',
        },
        {
          type: 'quiz',
          title: 'Illegal castling',
          question: 'In which case is castling NOT allowed?',
          options: [
            { text: 'The king is in check', correct: true, why: 'You cannot castle out of check. Deal with the check first.' },
            { text: 'A rook stands on an open file', why: 'Open files do not matter. Only movement, blockers, and attacked squares do.' },
            { text: 'A pawn has just been captured', why: 'Captures elsewhere are irrelevant. Castling only cares about king and rook.' },
          ],
        },
        {
          type: 'demo',
          title: 'En passant',
          body: [
            'When an enemy pawn makes its two-square jump and lands beside your pawn, you may capture it as if it had moved only one square.',
            'The catch: only immediately, on your very next move. Wait one move and the chance is gone forever.',
          ],
          fen: '4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 2',
          moves: ['exd6'],
          caption: 'exd6 en passant — the black pawn is gone',
        },
        {
          type: 'exercise',
          title: 'Catch it in time',
          body: ['Black just played b7–b5, jumping past your pawn on c5. Punish it right now.'],
          fen: '4k3/8/8/1pP5/8/8/8/4K3 w - b6 0 2',
          solution: ['cxb6'],
          goal: 'Capture en passant',
          hint: 'Take as if the b-pawn had only moved one square.',
          success: 'The only chance you will ever get — and you took it.',
        },
        {
          type: 'demo',
          title: 'Promotion',
          body: [
            'A pawn that reaches the last rank stops being a pawn: it becomes a queen, rook, bishop, or knight — your choice.',
            'Almost always take the queen. Promotions decide endgames more than any other factor.',
          ],
          fen: '8/1P6/8/8/4k3/8/8/4K3 w - - 0 1',
          moves: ['b8=Q'],
          caption: 'A new queen enters the board',
        },
        {
          type: 'exercise',
          title: 'Promote with mate',
          body: ['Your pawn is one square from glory. There is a mate waiting — find it.'],
          fen: 'k7/2P5/1K6/8/8/8/8/8 w - - 0 1',
          solution: ['c8=Q#'],
          goal: 'Mate in one by promoting',
          hint: 'Promote on c8. The black king on a8 will have nowhere to run.',
          success: 'c8=Q#. Promotion and checkmate in a single move — the dream endgame finish.',
        },
        {
          type: 'quiz',
          title: 'Underpromotion',
          question: 'When might you promote to something other than a queen?',
          options: [
            { text: 'When a knight would fork or mate where a queen would not', correct: true, why: 'Knight promotions create mate patterns or forks the queen cannot copy. Rare but real.' },
            { text: 'To avoid a threefold repetition', why: 'Promotion choice has nothing to do with repetition.' },
            { text: 'Never — always take the queen', why: 'Not quite. There are famous positions where a knight promotion is the only win or the only mate.' },
          ],
        },
        {
          type: 'text',
          title: 'Draws',
          body: [
            'Not every game ends in a mate. The five draw rules you must know:',
            'Stalemate — the side to move is not in check but has no legal move. The game is a draw, no matter how much material the other side has.',
            'Threefold repetition — the same position occurs three times. Either player can claim the draw.',
            'The fifty-move rule — fifty moves by each side with no capture and no pawn move. Draw.',
            'Insufficient material — king versus king, or king and minor piece versus king, cannot be won.',
            'Agreement — both players simply agree to a draw.',
          ],
          keyIdea: 'Winning by stalemate is impossible. Watch for it when you are ahead.',
        },
        {
          type: 'exercise',
          title: 'Do not throw away the win',
          body: [
            'Black\'s king is cornered. One careless queen move here lets him off with a stalemate — a draw.',
            'Find the mate instead.',
          ],
          fen: '7k/8/6K1/Q7/8/8/8/8 w - - 0 1',
          solution: ['Qa8#'],
          goal: 'Mate in one — avoid the stalemate',
          hint: 'Pin the king to the last rank with a check along the 8th.',
          success: 'Mate. Qd5?? instead would have been stalemate — the classic way to throw away a completely won game.',
          explanation: 'After Qd5?? Black would not be in check but could not move: stalemate, draw. Qa8# keeps the check on and takes every escape square.',
        },
      ],
    },
    {
      id: 'check-and-mate',
      title: 'Check, mate & stalemate',
      subtitle: 'How attacks on the king work, and how to finish the job.',
      minutes: 10,
      steps: [
        {
          type: 'text',
          title: 'What check means',
          body: [
            'Check = the king is attacked. You must answer it, this move, with exactly one of three things:',
            'Move the king to a safe square. Block the attack with another piece. Capture the attacker.',
            'If none of the three exists, it is checkmate and the game is over.',
          ],
          keyIdea: 'Three answers to check: move, block, capture. Nothing else.',
        },
        {
          type: 'quiz',
          title: 'Answering check',
          question: 'Your king is in check. Which of these is NOT a legal response?',
          options: [
            { text: 'Castling', correct: true, why: 'You may never castle while in check — or through it, or into it.' },
            { text: 'Blocking with a piece', why: 'Blocking works for checks from sliding pieces along a line.' },
            { text: 'Capturing the attacker', why: 'Removing the attacker always ends the check.' },
          ],
        },
        {
          type: 'demo',
          title: 'The back-rank mate',
          body: [
            'The most common mate in club chess. The king is trapped behind his own pawns; a rook (or queen) slides into the last rank.',
            'The cure, played before it happens: make a little "air" with a pawn move like h3.',
          ],
          fen: '6k1/5ppp/8/8/8/8/8/4R2K w - - 0 1',
          moves: ['Re8#'],
          caption: 'Re8 — mate on the back rank',
        },
        {
          type: 'exercise',
          title: 'Break through the back rank',
          body: ['Both kings are entombed by their pawns. You have the first shot — take it.'],
          fen: '3r2k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1',
          solution: ['Rxd8#'],
          goal: 'Mate in one',
          hint: 'The black rook is the only defender on the back rank. Remove it — with tempo.',
          success: 'You captured the defender and mated on the same move. That combination wins countless games.',
        },
        {
          type: 'exercise',
          title: 'Answer the check',
          body: ['Black\'s rook has invaded your first rank. There is exactly one way out — find it.'],
          fen: 'k7/8/8/8/8/8/5PPP/3Rr1K1 w - - 0 1',
          solution: ['Rxe1'],
          goal: 'Escape the check',
          hint: 'The king cannot move: every square is covered. Can a piece of yours reach the attacker?',
          success: 'Rxe1. Your rook removed the attacker — the simplest and best answer to check.',
        },
        {
          type: 'demo',
          title: 'Support mate: king helps',
          body: [
            'Near the corner, the king steps up to guard the queen\'s landing square. Queen checks, king protects: mate.',
            'This "queen + king" duel is the ending you must win in probably half your endgames.',
          ],
          fen: '7k/8/6K1/8/8/8/8/Q7 w - - 0 1',
          moves: ['Qa8#'],
          caption: 'The king guards, the queen delivers',
        },
        {
          type: 'exercise',
          title: 'Break the wall',
          body: ['A rook guards the back rank and a pawn shields the king. The long diagonal is open...'],
          fen: '4r2k/6p1/6K1/8/8/8/1Q6/8 w - - 0 1',
          solution: ['Qxg7#'],
          goal: 'Mate in one',
          hint: 'The pawn on g7 is defended by the black king — but yours defends your queen. Count attackers and defenders.',
          success: 'Qxg7#. Your king protected the capture, so the black king could not take back. King safety wins again.',
        },
        {
          type: 'quiz',
          title: 'Stalemate or mate?',
          question: 'Black to move: king on h8, White has king g6 and queen f7. What is the result?',
          options: [
            { text: 'Stalemate — the game is drawn', correct: true, why: 'Black is not in check but has no legal move. That is a draw, even up a queen.' },
            { text: 'Checkmate for White', why: 'The king is not actually attacked. Without check there is no mate.' },
            { text: 'Black must play Kg8', why: 'g8 is covered by the queen on f7. Black has no moves at all.' },
          ],
        },
        {
          type: 'text',
          title: 'What comes next',
          body: [
            'You now know every rule of chess. From here the game becomes about judgment: where the pieces belong, when to attack, when to trade.',
            'The next level covers the opening — the part of the game where most beginners lose before move ten.',
          ],
        },
      ],
    },
  ],
}
