import type { Level } from '../schema'

export const level2: Level = {
  id: 'opening-play',
  n: 2,
  title: 'Opening Play',
  tagline: 'Start every game with a plan instead of a coin flip.',
  color: '#4f8f4a',
  lessons: [
    {
      id: 'opening-principles',
      title: 'Opening principles',
      subtitle: 'Four rules that carry you through the first ten moves of almost any game.',
      minutes: 12,
      steps: [
        {
          type: 'text',
          title: 'What the opening is for',
          body: [
            'The opening has exactly three goals, in this order:',
            '1. Claim the center. Pawns on e4/d4 (or e5/d5 for Black) give your pieces room and your opponent less.',
            '2. Develop your pieces. Knights and bishops out of the starting squares, onto squares where they see the action.',
            '3. Keep the king safe. Castle, usually within the first ten moves.',
            'Most strong openings obey these three rules. Most losing openings break one.',
          ],
          keyIdea: 'Center first. Pieces second. King safety third. Tempo throughout.',
        },
        {
          type: 'quiz',
          title: 'First moves',
          question: 'Which first move immediately fights for the center?',
          options: [
            { text: '1.e4', correct: true, why: 'It opens lines for the queen and bishop and claims squares on d5 and f5.' },
            { text: '1.h4', why: 'A rook pawn does nothing for the center or your pieces.' },
            { text: '1.a4', why: 'Same problem — the edge is the wrong place to start.' },
            { text: '1.g4', why: 'It even weakens the king. Grob\'s Attack has fans, but not in this lesson.' },
          ],
        },
        {
          type: 'demo',
          title: 'A model opening',
          body: [
            'This is the Italian Game after 1.e4 e5 2.Nf3 Nc6 3.Bc4. Look what White has built:',
            'The pawn on e4 owns d5 and f5. The knight on f3 hits e5. The bishop on c4 stares at f7 — the weakest square in Black\'s camp, guarded only by the king.',
            'Every move did a job. Nothing moved twice. That is the whole recipe.',
          ],
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
          arrows: [
            { from: 'e4', to: 'd5', color: 'green' },
            { from: 'f3', to: 'e5', color: 'green' },
            { from: 'c4', to: 'f7', color: 'red' },
          ],
          caption: 'White: pawn on e4, Nf3, Bc4 — three moves, three jobs',
        },
        {
          type: 'exercise',
          title: 'Develop with tempo',
          body: [
            '1.e4 e5. It is move two. Develop a piece AND attack something — the strongest way to develop.',
          ],
          fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
          solution: ['Nf3'],
          goal: 'Develop with an attack on e5',
          hint: 'Which knight move lands where it attacks the black pawn on e5?',
          success: 'Nf3 develops the knight and hits e5. Black must react to your development. That is tempo.',
        },
        {
          type: 'demo',
          title: 'The queen raid that fails',
          body: [
            'Watch White bring the queen out on move two. 1.e4 e5 2.Qh5 — attacking e5 and threatening mate on f7.',
            'Black chases her: 2...g6, then 3.Qxe5+ grabs a pawn with check. But look at the cost: White\'s queen has made three moves while Black developed. After 3...Qe7 Black is fully ready to kick her again.',
            'The queen comes back to d1 eventually, and White is five tempi behind. Early queen raids win pawns and lose games.',
          ],
          fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
          moves: ['Qh5', 'g6', 'Qxe5+', 'Qe7'],
          caption: 'Three queen moves, zero development',
        },
        {
          type: 'quiz',
          title: 'When to castle',
          question: 'What is a healthy castling schedule?',
          options: [
            { text: 'Usually within the first 8–10 moves', correct: true, why: 'Early enough to be safe, late enough that you developed first.' },
            { text: 'Never — the king fights best in the center', why: 'In the opening the center is exactly where the fighting is. Kings do not fight there.' },
            { text: 'After every piece has moved', why: 'Too slow. Development and king safety go hand in hand.' },
          ],
        },
        {
          type: 'exercise',
          title: 'Safety first',
          body: ['The Italian position again. Development is done for now — finish the job.'],
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
          solution: ['O-O'],
          goal: 'Castle kingside',
          hint: 'The two-piece move. f1 and g1 are clear.',
          success: 'Castled. From here White can play d3 or c3 and complete a model opening.',
        },
        {
          type: 'text',
          title: 'Tempo and pawn moves',
          body: [
            'A tempo is one unit of time — one move. Games at club level are usually decided by who wasted fewer.',
            'The biggest tempo leaks: moving the same piece twice for no reason, bringing the queen early, and pushing too many pawns.',
            'Pawns cannot move backward. Every pawn move permanently changes the structure. Ask what the move does: does it fight for the center, open a line for a piece, or gain time? If the answer is nothing — do not play it.',
          ],
          keyIdea: 'One move, one job. Ask what every move does for your position.',
        },
        {
          type: 'playout',
          title: 'Play the opening yourself',
          body: [
            'You are White against a weak opponent. Reach move 10 with all three goals done: pawns in the center, pieces developed, king castled.',
            'If you drop more than two pawns of material on the way, the step fails.',
          ],
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          side: 'w',
          goal: 'Castle by move 10 without losing material',
          engineLevel: 2,
          success: 'castle',
          maxMoves: 10,
          successText: 'Textbook opening. Center, development, king safety — all three, on time.',
          failText: 'Not quite. Remember the order: center, develop, castle. Try again.',
        },
      ],
    },
    {
      id: 'first-openings',
      title: 'Your first openings',
      subtitle: 'One plan for White, one answer to 1.e4, one answer to 1.d4. That is all you need.',
      minutes: 14,
      steps: [
        {
          type: 'text',
          title: 'Openings are plans, not scripts',
          body: [
            'You do not need to memorize twenty moves of theory. You need three small, sound systems whose IDEAS you understand.',
            'For White: the Italian Game — attack the center, put a bishop on c4, castle, then play c3 and d4 when ready.',
            'Against 1.e4: meet it with 1...e5 and mirror the same healthy ideas.',
            'Against 1.d4: meet it with 1...d5 and keep a solid pawn chain.',
          ],
        },
        {
          type: 'demo',
          title: 'The Italian Game',
          body: [
            '1.e4 e5 2.Nf3 Nc6 3.Bc4 — the Italian Game, played for 500 years.',
            'The plan: quick development, the bishop aimed at f7, then c3 supporting a future d4 push that takes over the center.',
            'Notice both sides castle quickly and the middlegame starts with all pieces working.',
          ],
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4'],
          caption: 'The Italian Game — three moves, three jobs',
        },
        {
          type: 'quiz',
          title: 'Why c4?',
          question: 'In the Italian Game, what is the bishop on c4 aiming at?',
          options: [
            { text: 'f7 — defended only by the king', correct: true, why: 'f7 is the softest square in Black\'s position. Even the threat of Bxf7 shapes Black\'s play.' },
            { text: 'a6, to win a pawn', why: 'a6 is a corner pawn. The bishop is not going there.' },
            { text: 'Nothing — it is just a developing move', why: 'It develops, yes, but the diagonal to f7 is the entire point of c4 over other bishop squares.' },
          ],
        },
        {
          type: 'exercise',
          title: 'Play the Italian, move by move',
          body: [
            'You are White. Play the first moves of the Italian Game. Black\'s replies are played for you.',
          ],
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          solution: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4'],
          goal: 'e4, Nf3, Bc4 — in that order',
          hint: 'Pawn to the center first, then the kingside knight, then the bishop that eyes f7.',
          success: 'That is the Italian Game. You just played what grandmasters play after 1.e4 e5.',
        },
        {
          type: 'demo',
          title: 'Black\'s side of it',
          body: [
            'The Giuoco Piano ("quiet game"): both sides play the same healthy moves. 3...Bc5 mirrors White and prepares to castle.',
            'Black wants the same things you want: the center (e5), development (Nc6, Bc5), king safety (0-0). Symmetry is fine when the moves are good.',
          ],
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'],
          caption: 'Giuoco Piano — both sides develop',
        },
        {
          type: 'exercise',
          title: 'Answer 1.e4',
          body: ['You are Black. White opens with 1.e4. Play the classical response.'],
          fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1',
          solution: ['e5'],
          goal: 'Claim your share of the center',
          hint: 'Mirror the pawn into the center. e5.',
          success: '1...e5. You matched White in the center and opened your own queen and bishop.',
        },
        {
          type: 'exercise',
          title: 'Develop the knight',
          body: ['After 1.e4 e5 2.Nf3, it is your move.'],
          fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2',
          solution: ['Nc6'],
          goal: 'Defend e5 with a developing move',
          hint: 'The e5 pawn is attacked. Defend it with a piece, not a pawn.',
          success: 'Nc6 defends e5 and develops. Defending with developing moves is the whole trick.',
        },
        {
          type: 'exercise',
          title: 'The bishop pair mirrors',
          body: ['After 1.e4 e5 2.Nf3 Nc6 3.Bc4, play the symmetrical developing move.'],
          fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
          solution: ['Bc5'],
          goal: 'Develop the f8 bishop actively',
          hint: 'Your light-squared bishop is stuck behind the e5 pawn. Bring out the other one.',
          success: 'Bc5 — the Giuoco Piano. Your bishop eyes f2 the same way White\'s eyes f7.',
        },
        {
          type: 'demo',
          title: 'Against 1.d4',
          body: [
            'When White opens with the queen\'s pawn, the healthy reply is 1...d5, then against the Queen\'s Gambit (2.c4) the simple 2...e6 keeps a solid chain.',
            'Black\'s structure — d5 and e6 — is a wall. White gains some space; Black gets a rock. Solid chess follows.',
          ],
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          moves: ['d4', 'd5', 'c4', 'e6'],
          caption: 'Queen\'s Gambit Declined — the wall',
        },
        {
          type: 'quiz',
          title: 'The gambit question',
          question: '1.d4 d5 2.c4 is the Queen\'s Gambit. Should Black grab the pawn with 2...dxc4?',
          options: [
            { text: 'Usually not — it hands White time to build the center', correct: true, why: 'After dxc4 White plays e4 with a big center while Black struggles to hit back. Taking is playable but not the beginner route.' },
            { text: 'Always — free pawns are free', why: 'It is not free. White wins it back or uses the time to take the whole center.' },
            { text: 'Never — the pawn is poisoned', why: 'Too strong a word: 2...dxc4 is a real opening (the Queen\'s Gambit Accepted). It is just harder to handle.' },
          ],
        },
        {
          type: 'text',
          title: 'What next',
          body: [
            'Three systems, all built on the same principles. Play them for a hundred games and you will notice you already understand openings better than most club players.',
            'Deeper opening study makes sense later — after tactics. Tactics decide more games than theory ever will.',
          ],
        },
      ],
    },
    {
      id: 'classic-traps',
      title: 'Classic traps',
      subtitle: 'Three famous traps — how they work, and how never to fall for one.',
      minutes: 12,
      steps: [
        {
          type: 'text',
          title: 'How traps actually work',
          body: [
            'A trap is not a trick — it is a bet that you will take material without checking the consequences.',
            'Every trap in this lesson fails the same way if you ask one question before grabbing anything: "If I take this, what is my opponent\'s next move?"',
            'Learn these three as both attacker and defender. You will land them, and you will dodge them.',
          ],
        },
        {
          type: 'demo',
          title: 'The Scholar\'s Mate',
          body: [
            '1.e4 e5 2.Bc4 Nc6 3.Qh5 — threatening Qxf7# because the bishop on c4 supports the queen.',
            'Black defended the wrong thing: 3...Nf6?? develops a knight but does nothing about f7.',
            '4.Qxf7# — checkmate. The king cannot take the queen (the bishop guards her) and cannot run.',
          ],
          fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
          moves: ['Bc4', 'Nc6', 'Qh5', 'Nf6', 'Qxf7#'],
          caption: 'Wait — this demo starts mid-game. The moves shown run from 1.e4 e5.',
        },
        {
          type: 'quiz',
          title: 'Defending f7',
          question: 'You are Black after 1.e4 e5 2.Bc4 Nc6 3.Qh5. Which reply LOSES at once?',
          options: [
            { text: '3...Nf6', correct: true, why: 'It develops, but ignores f7 — and Qxf7# is mate. The most famous blunder in chess.' },
            { text: '3...Qe7', why: 'The queen defends f7. Safe, if a little passive.' },
            { text: '3...g6', why: 'It blocks the h5–f7 diagonal and attacks the queen. White must retreat.' },
            { text: '3...Nh6', why: 'The knight defends f7 from h6. Playable.' },
          ],
        },
        {
          type: 'exercise',
          title: 'Punish the Scholar\'s Mate attempt',
          body: [
            'You are White: 1.e4 e5 2.Bc4 Nc6 3.Qh5 Nf6?? — Black walked into it. Finish the game.',
          ],
          fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
          solution: ['Qxf7#'],
          goal: 'Mate in one',
          hint: 'The queen on h5 and bishop on c4 both look at f7. What stops Kxf7? Nothing good.',
          success: 'Qxf7#. The bishop made the queen untouchable. That is the pattern: queen + bishop on f7.',
        },
        {
          type: 'demo',
          title: 'The Légal Trap',
          body: [
            'Older than the Scholar\'s Mate and much more beautiful. 1.e4 e5 2.Nf3 d6 3.Bc4 Bg4 4.Nc3 g6.',
            '5.Nxe5! — the knight offers itself. If Black takes the QUEEN instead, 5...Bxd1??, then 6.Bxf7+ Ke7 7.Nd5# — mate with two minor pieces while the white queen is already dead.',
            'The hidden point of 7.Nd5 is that the OTHER knight on e5 covers d7. Count every defender before you celebrate.',
            'If Black is calmer (5...Nxe5), White has simply won a pawn with 6.Qxg4.',
          ],
          fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
          moves: ['Nf3', 'd6', 'Bc4', 'Bg4', 'Nc3', 'g6', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
          caption: 'The queen dies — and so does Black',
        },
        {
          type: 'exercise',
          title: 'Deliver the Légal mate',
          body: [
            'The trap has been sprung: Black grabbed the queen. It is mate in one.',
          ],
          fen: 'rn1q1bnr/ppp1kB1p/3p2p1/4N3/4P3/2N5/PPPP1PPP/R1Bb1K1R w KQ - 1 7',
          solution: ['Nd5#'],
          goal: 'Mate in one',
          hint: 'The knight from c3. The other knight on e5 has already covered the king\'s flight square.',
          success: 'Nd5# — the Légal mate. A queen down, and the game is over anyway.',
        },
        {
          type: 'quiz',
          title: 'Reading 5.Nxe5',
          question: 'After 5.Nxe5! in the Légal position, what is White actually threatening?',
          options: [
            { text: 'Two things: ...Bxd1?? loses to the mating attack, and ...Nxe5?? loses the g4 bishop to Qxg4', correct: true, why: 'The knight is untouchable either way. That is what makes it a real trap rather than a bluff.' },
            { text: 'Nothing — it is a mistake that drops a knight', why: 'Look again: capture the knight with ...Nxe5 and the bishop on g4 is hanging to the queen.' },
            { text: 'A knight fork on f7', why: 'Not the main point. The threat structure is about the queen and the g4 bishop.' },
          ],
        },
        {
          type: 'text',
          title: 'The habit that beats every trap',
          body: [
            'Before any capture — especially a free piece — ask three questions:',
            'What did my opponent just threaten with that move? Is the piece I want to take actually defended enough? And after I take, what is their best follow-up?',
            'Traps do not catch players who count. Counting takes two seconds; losing the queen takes the game.',
          ],
          keyIdea: 'Free pieces are bait until you have counted defenders twice.',
        },
      ],
    },
  ],
}
