// Graduation lines: one honest "superpower" sentence per level, shown on the
// completion card as "You can now ...". Written per level, not generated, and
// kept falsifiable: each line names exactly what the level's drills made the
// learner do on the board.

export const GRADUATION: Record<string, string> = {
  // Newbie
  'nb-01': 'read any chess position: every square has a name, and you speak the language.',
  'nb-02': 'move pawns with purpose: straight ahead, capturing diagonally, never back.',
  'nb-03': 'jump a knight over a wall of pawns, straight to the square it hurts most.',
  'nb-04': 'send a bishop down an open diagonal, and you know why it stays on one color forever.',
  'nb-05': 'own an open file with your rook and threaten the whole seventh rank.',
  'nb-06': 'punish an early queen raid, and win a rook with check first, capture second.',
  'nb-07': 'walk your king into an endgame like a fighter, one careful step at a time.',
  'nb-08': 'answer any check calmly: capture the attacker, block, or run.',
  'nb-09': 'spot the back-rank mate coming, and deliver one yourself.',
  'nb-10': 'castle at the right moment, on the right side, for king safety and an active rook.',
  'nb-11': 'catch an en passant capture in its one-move window, and know when it has expired.',
  'nb-12': 'promote a pawn to a queen, with check or mate when it counts.',
  'nb-13': 'finish a won game: mate with queen and king, and never hand back a draw by stalemate.',
  'nb-14': 'count any trade in points and know instantly whether it profits you.',
  'nb-15': 'run the safety scan: their checks, their captures, their threats, before every move.',
  'nb-16': 'find and punish undefended pieces against a live opponent.',
  'nb-17': 'give check with a plan, and escape a check by running the three-answer list.',
  'nb-18': 'castle, en passant, promote, and underpromote to mate, all under pressure.',
  'nb-19': 'play a real opening plan: center, development, king safety, move by move.',
  'nb-20': 'play a full game with every rule in the book, and the Légal trap is yours to spring.',
  // Beginner
  'bg-01': 'fight for the center on move one, and explain why flank pawns waste time.',
  'bg-02': 'develop a new piece every move instead of shuffling one.',
  'bg-03': 'castle early and know what both of your pieces gain from it.',
  'bg-04': 'run the blunder check that saves hundreds of points of material.',
  'bg-05': 'fork two pieces with one move, and take the bigger prize.',
  'bg-06': 'pin a piece to its king and watch it freeze.',
  'bg-07': 'skewer: chase the king off a line and collect what it leaves behind.',
  'bg-08': 'spot loose pieces on both sides before they decide the game.',
  'bg-09': 'count attackers against defenders, with values, before any capture.',
  'bg-10': 'remove the defender first, then collect the prize it was guarding.',
  'bg-11': 'make luft in time, so the back-rank mate never happens to you.',
  'bg-12': 'mate with two rooks using the ladder, the most reliable mate in chess.',
  'bg-13': 'mate with queen and king by shrinking the box, without stalemate slips.',
  'bg-14': 'create a passed pawn and shepherd it down the board.',
  'bg-15': 'find forks, pins and skewers in mixed positions, not textbook ones.',
  'bg-16': 'defend: counting, loose pieces, and the safe recapture.',
  'bg-17': 'play the Italian Game with a real plan behind every move.',
  'bg-18': 'play a full development game and castle by move 12.',
  'bg-19': 'punish Scholar’s Mate on sight and run the three-second scan on autopilot.',
  'bg-20': 'finish the Beginner tier with a complete game on the board.',
  // Intermediate
  'int-01': 'hit two targets with one move, whatever the piece.',
  'int-02': 'unmask a hidden attacker by moving the piece in front of it.',
  'int-03': 'play the zwischenzug: the in-between move that ruins forced lines.',
  'int-04': 'deflect a defender off its post, then strike where it stood.',
  'int-05': 'decoy to a doomed square and clear a road with tempo.',
  'int-06': 'plant a knight on an outpost it can never be evicted from.',
  'int-07': 'seize the open file, double on it, and park a rook on the seventh.',
  'int-08': 'name the pawn structure sins and punish them before they cost you.',
  'int-09': 'tell a good bishop from a bad one, and fix or exploit either.',
  'int-10': 'fire the whole tactical arsenal in mixed positions.',
  'int-11': 'storm the castled king where its walls are thinnest.',
  'int-12': 'defend with technique: trade the attacker, hold the line, hit back.',
  'int-13': 'create two weaknesses where one defense used to hold.',
  'int-14': 'use your king as a fighting piece and win the opposition.',
  'int-15': 'win pawn endings with the square rule and clean pawn races.',
  'int-16': 'cut the king off and convert rook endings that matter.',
  'int-17': 'convert an advantage instead of letting it evaporate.',
  'int-18': 'hold endgame technique together under real pressure.',
  'int-19': 'mix tactics and technique in one sitting, and keep your head.',
  'int-20': 'graduate the tier with a famous pattern, an exam, and a full game behind you.',
  // Advanced
  'adv-01': 'generate candidate moves in the master order: checks, captures, threats.',
  'adv-02': 'run the blunder check before every move: what is his best reply?',
  'adv-03': 'sacrifice for the attack when the king has nowhere to hide.',
  'adv-04': 'batter open the wall around a castled king.',
  'adv-05': 'counterattack instead of defending passively.',
  'adv-06': 'exploit a weak color complex before anyone else sees it.',
  'adv-07': 'blockade, and build deep outposts that are addresses, not stops.',
  'adv-08': 'use a space advantage to outmaneuver without trading.',
  'adv-09': 'attack a pawn chain at its base, and know when to release the tension.',
  'adv-10': 'calculate forcing lines under real time pressure.',
  'adv-11': 'choose openings by the plans and endgames they promise.',
  'adv-12': 'handle the isolated queen pawn, with and without it.',
  'adv-13': 'win the Lucena position with the bridge, every time.',
  'adv-14': 'hold the Philidor position with rear checks, every time.',
  'adv-15': 'activate rooks: cutting off, behind passed pawns, and the active king.',
  'adv-16': 'judge opposite-bishop endings, and push the outside passed pawn that matters.',
  'adv-17': 'argue knight versus bishop with structure, not superstition.',
  'adv-18': 'navigate queen endings: checks, forks, and the perpetual road.',
  'adv-19': 'convert winning endgames by centralizing and simplifying.',
  'adv-20': 'clear the Advanced exam, a famous game, and a tier of new habits.',
  // Master
  'ms-01': 'think in imbalances instead of counting points.',
  'ms-02': 'play prophylaxis: take what he wants before he takes it.',
  'ms-03': 'spend material to buy the tempo that mates.',
  'ms-04': 'launch a minority attack or push a majority, by pawn geography.',
  'ms-05': 'separate permanent weaknesses from temporary ones.',
  'ms-06': 'trade with intent: name which pieces stay and which pieces go.',
  'ms-07': 'plan by square color and own the complex the position hands you.',
  'ms-08': 'imprison passed pawns with a blockade that holds.',
  'ms-09': 'know when the clock on your dynamic advantage expires.',
  'ms-10': 'apply the full master toolkit in live positions.',
  'ms-11': 'steer openings toward the endgames you want to play.',
  'ms-12': 'defend rook endings with short-side technique and checking distance.',
  'ms-13': 'build fortresses, and refuse to crack them.',
  'ms-14': 'wield the outside passed pawn in opposite-bishop endings.',
  'ms-15': 'race pawns on opposite wings with everything on the line.',
  'ms-16': 'defend difficult positions with activity, not hope.',
  'ms-17': 'manage clock, tilt, and tempo bluffs like a professional.',
  'ms-18': 'calculate deep, verified combinations.',
  'ms-19': 'combine multiple motifs at full depth.',
  'ms-20': 'out-plan club players: prophylaxis first, trades with intent, defense by counterattack.',
  // Grandmaster
  'gm-01': 'prune calculation trees and trust only verified endings.',
  'gm-02': 'find resources in worse positions: activity, counterplay, the perpetual.',
  'gm-03': 'win, and escape, positions of pure zugzwang.',
  'gm-04': 'build fortresses and break the ones built against you.',
  'gm-05': 'make structural exchanges on purpose, bad piece for good square.',
  'gm-06': 'launch flank thrusts that start revolutions.',
  'gm-07': 'sacrifice the exchange for structure, squares, and time.',
  'gm-08': 'restrict his moves before making your own, at the highest level.',
  'gm-09': 'walk your king across the board while the game still burns.',
  'gm-10': 'handle passed pawns by doctrine: blockaders, duos, the far-advanced killer.',
  'gm-11': 'convert rook-and-pawn endings with Lucena and clean cutting off.',
  'gm-12': 'hold every draw you must know, on demand.',
  'gm-13': 'execute pure technique: one endgame, zero mistakes.',
  'gm-14': 'calculate when the position has no forcing answer.',
  'gm-15': 'prepare like a professional: a dossier, not memorized lines.',
  'gm-16': 'analyze your own games with a blunder map and a plan audit.',
  'gm-17': 'spend clock minutes where the position is actually complex.',
  'gm-18': 'produce grandmaster combinations at full forcing depth.',
  'gm-19': 'weave multiple motifs into one finish, endgame included.',
  'gm-20': 'read any position like a grandmaster: prune the tree, kill the plan, convert the point.',
}
