// Candidate batch A: 25 easy/medium puzzles (rating 350-950) for the Rush pool.
// Drafted by hand, every one goes through scripts/verify-puzzles.ts before shipping.
import type { Puzzle } from '../src/content/schema'

export const CANDIDATES: Puzzle[] = [
  {
    id: 'p-rank-squeeze',
    fen: '6k1/5ppp/6R1/8/8/8/8/1R4K1 w - - 0 1',
    solution: 'Rb8#',
    rating: 450,
    themes: ['mate'],
    title: 'Two rooks, one rank',
  },
  {
    id: 'p-anastasia-pattern',
    fen: '7k/4N1p1/8/8/8/8/8/5KR1 w - - 0 1',
    solution: 'Rh1#',
    rating: 700,
    themes: ['mate'],
    title: 'Anastasia finishes',
  },
  {
    id: 'p-queen-box-center',
    fen: '3k4/8/3K4/8/8/8/8/1Q6 w - - 0 1',
    solution: 'Qb8#',
    rating: 400,
    themes: ['mate', 'endgame'],
    title: 'Box mate in the center',
  },
  {
    id: 'p-two-rooks-7th',
    fen: '7k/R7/8/8/8/8/8/1R5K w - - 0 1',
    solution: 'Rb8#',
    rating: 500,
    themes: ['mate'],
    title: 'The ladder closes',
  },
  {
    id: 'p-damiano-pattern',
    fen: '7k/7p/6P1/8/8/8/7Q/6K1 w - - 0 1',
    solution: 'Qxh7#',
    rating: 550,
    themes: ['mate'],
    title: 'Damiano finishes',
  },
  {
    id: 'p-black-backrank',
    fen: 'r7/4k3/8/8/8/8/5PPP/6K1 b - - 0 1',
    solution: 'Ra1#',
    rating: 500,
    themes: ['mate'],
    title: 'Black raids the back rank',
  },
  {
    id: 'p-single-rook-backrank',
    fen: '6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1',
    solution: 'Ra8#',
    rating: 450,
    themes: ['mate'],
    title: 'Back rank, no escape',
  },
  {
    id: 'p-queen-box-corner',
    fen: '7k/8/5K2/8/8/8/8/6Q1 w - - 0 1',
    solution: 'Qg7#',
    rating: 400,
    themes: ['mate', 'endgame'],
    title: 'Queen delivers in the corner',
  },
  {
    id: 'p-family-fork',
    fen: 'r3k3/3p4/8/1N6/8/8/6PP/6K1 w - - 0 1',
    solution: 'Nc7+ Kd8 Nxa8',
    rating: 750,
    themes: ['fork', 'winningMaterial'],
    title: 'The family fork',
  },
  {
    id: 'p-royal-fork-queen',
    fen: '3q1k2/8/8/8/3N4/8/5PPP/6K1 w - - 0 1',
    solution: 'Ne6+ Ke8 Nxd8',
    rating: 800,
    themes: ['fork', 'winningMaterial'],
    title: 'Forked king and queen',
  },
  {
    id: 'p-black-family-fork',
    fen: '5k2/8/8/8/8/4n3/8/R3K3 b - - 0 1',
    solution: 'Nc2+ Kd2 Nxa1',
    rating: 750,
    themes: ['fork', 'winningMaterial'],
    title: 'Black forks back',
  },
  {
    id: 'p-fork-king-knight',
    fen: '3r3k/8/8/6N1/8/8/5PPP/6K1 w - - 0 1',
    solution: 'Nf7+ Kg8 Nxd8',
    rating: 800,
    themes: ['fork', 'winningMaterial'],
    title: 'Check, then the rider falls',
  },
  {
    id: 'p-black-queen-skewer',
    fen: 'q7/7k/8/8/3K4/8/8/6R1 b - - 0 1',
    solution: 'Qa7+ Kc4 Qxg1',
    rating: 750,
    themes: ['skewer', 'winningMaterial'],
    title: 'Black skewers first',
  },
  {
    id: 'p-queen-skewer-diagonal',
    fen: '7q/8/8/4k3/8/2P5/5B2/6K1 w - - 0 1',
    solution: 'Bd4+ Kd6 Bxh8',
    rating: 750,
    themes: ['skewer', 'winningMaterial'],
    title: 'Bishop skewers the long diagonal',
  },
  {
    id: 'p-rank-skewer',
    fen: '8/8/8/4k2r/8/8/8/R5K1 w - - 0 1',
    solution: 'Ra5+ Kd6 Rxh5',
    rating: 600,
    themes: ['skewer', 'winningMaterial'],
    title: 'Down the fifth rank',
  },
  {
    id: 'p-long-diagonal-skewer',
    fen: '8/6r1/8/4k3/8/2P1B3/5PPP/6K1 w - - 0 1',
    solution: 'Bd4+ Ke6 Bxg7',
    rating: 650,
    themes: ['skewer', 'winningMaterial'],
    title: 'The long diagonal bites',
  },
  {
    id: 'p-bishop-double-strike',
    fen: '7k/8/8/8/8/7P/5PPK/r1B5 w - - 0 1',
    solution: 'Bb2+ Kh7 Bxa1',
    rating: 750,
    themes: ['doubleAttack', 'winningMaterial'],
    title: 'The bishop hits two targets',
  },
  {
    id: 'p-double-check-queen',
    fen: '3k4/4q3/8/8/3N4/8/8/3R2K1 w - - 0 1',
    solution: 'Nc6+ Ke8 Nxe7',
    rating: 900,
    themes: ['discoveredAttack', 'winningMaterial'],
    title: 'Double check takes the queen',
  },
  {
    id: 'p-promo-mate',
    fen: '7k/5P2/6K1/8/8/8/8/8 w - - 0 1',
    solution: 'f8=Q#',
    rating: 500,
    themes: ['promotion', 'mate', 'endgame'],
    title: 'Promotion with a punchline',
  },
]
